In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader, random_split, RandomSampler, SequentialSampler

!pip install transformers
from transformers import GPT2LMHeadModel,  GPT2Tokenizer, GPT2Config, GPT2LMHeadModel
from transformers import AdamW, get_linear_schedule_with_warmup
import json

import pandas as pd  

     |████████████████████████████████| 4.0 MB 32.5 MB/s 
     |████████████████████████████████| 880 kB 56.2 MB/s 
     |████████████████████████████████| 6.6 MB 53.3 MB/s 
     |████████████████████████████████| 84 kB 3.5 MB/s 
     |████████████████████████████████| 596 kB 67.8 MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895260 sha256=1c596ff0054c6e0db15fd811e4bdcb71b3fa00970c3d959a78376dc9d98ae3f0
  Stored in directory: /root/.cache/pip/wheels/87/39/dd/a83eeef36d0bf98e7a4d1933a4ad2d660295a40613079bafc9
Successfully built sacremoses
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
tokenizer = GPT2Tokenizer.from_pretrained('gpt2', bos_token='<|BOS|>', eos_token='<|EOS|>', pad_token='<|pad|>') #gpt2-medium


class GPT2Dataset(Dataset):
  def __init__(self, txt_list, tokenizer, gpt2_type="gpt2", max_length=768):
    self.tokenizer = tokenizer
    self.input_ids = []
    self.attn_masks = []
    for txt in txt_list:
      encodings_dict = tokenizer('<|BOS|>'+ txt + '<|EOS|>', truncation=True, max_length=max_length, padding="max_length")
      self.input_ids.append(torch.tensor(encodings_dict['input_ids']))
      self.attn_masks.append(torch.tensor(encodings_dict['attention_mask']))
    
  def __len__(self):
    return len(self.input_ids)

  def __getitem__(self, idx):
    return self.input_ids[idx], self.attn_masks[idx] 

Downloading:   0%|          | 0.00/0.99M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [ ]:
# import pandas as pd
# xx = pd.read_csv('summary.csv', encoding = "ISO-8859-1")
# print(xx)

file = 'books_dataset.json'
with open(file) as train_file:
    dict_train = json.load(train_file)

# converting json dataset from dictionary to dataframe
train = pd.DataFrame.from_dict(dict_train, orient='index')
train.reset_index(level=0, inplace=True)

xx=train
# data = json.loads(books_dataset)
# df = pd.json_normalize(data['results'])
# xx = df
#print(xx.iloc[:,1])


In [ ]:


summaries = xx.iloc[:,1].copy()

print(summaries)

0      <|BOS|>The Time Machine<|SEP|>time faints his ...
1      <|BOS|>The War of the Worlds<|SEP|>envious eye...
2      <|BOS|>A Princess of Mars<|SEP|>lower atmosphe...
3      <|BOS|>Youth<|SEP|>space aliens tiny dead iden...
4      <|BOS|>2 B R 0 2 B<|SEP|>population control ac...
                             ...                        
280    <|BOS|>Rip Foster Rides the Gray Planet<|SEP|>...
281    <|BOS|>Eastern Standard Tribe<|SEP|>members ps...
282    <|BOS|>Man of Many Minds<|SEP|>minds a secret ...
283    <|BOS|>The Players<|SEP|>aliens not nonsense t...
284    <|BOS|>Rip Foster in Ride the Gray Planet<|SEP...
Name: 0, Length: 285, dtype: object


In [ ]:
dataset = GPT2Dataset(summaries, tokenizer, max_length=768)
train_size = int(0.7 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])


In [ ]:
def preprocess_val_dataset(dataset):
  
  s = tokenizer.decode(dataset[0][0]).split('<|SEP|>')
  new_output = s[len(s)-1]
  new_output = s[len(s)-1]
  new_input = s[0]
  for i in range(1,len(s)-1):
    new_input = new_input+'<|SEP|>'+s[i]

  new_input = new_input + '<|SEP|>'
  #print(new_input)
  input_ids = tokenizer.encode(new_input, return_tensors='pt')
  output_ids = tokenizer.encode(new_output, return_tensors='pt')

  return input_ids[0], torch.ones(len(input_ids[0])), output_ids, new_output, new_input

In [ ]:
batch_size=2
train_dataloader = DataLoader(
            train_dataset,  # The training samples.
            sampler = RandomSampler(train_dataset), # Select batches randomly
            batch_size = batch_size # Trains with this batch size.
        )
validation_dataloader = DataLoader(
            val_dataset, # The validation samples.
            sampler = SequentialSampler(val_dataset), # Pull out batches sequentially.
            batch_size = batch_size # Evaluate with this batch size.
        )

In [ ]:
configuration = GPT2Config.from_pretrained('gpt2', output_hidden_states=False)

# instantiate the model
model = GPT2LMHeadModel.from_pretrained("gpt2", config=configuration)

# this step is necessary because I've added some tokens (bos_token, etc) to the embeddings
# otherwise the tokenizer and model tensors won't match up
model.resize_token_embeddings(len(tokenizer))


Downloading:   0%|          | 0.00/523M [00:00<?, ?B/s]

Embedding(50260, 768)

In [ ]:
epochs = 5
learning_rate = 10e-4
warmup_steps = 1e2
epsilon = 1e-8

# this produces sample output every 100 steps
sample_every = 100

In [ ]:
optimizer = AdamW(model.parameters(),
                  lr = learning_rate,
                  eps = epsilon
                )

total_steps = len(train_dataloader) * epochs

# Create the learning rate scheduler.
# This changes the learning rate as the training loop progresses
scheduler = get_linear_schedule_with_warmup(optimizer, 
                                            num_warmup_steps = warmup_steps, 
                                            num_training_steps = total_steps)

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,


In [ ]:
import time
import datetime
import random
import tensorflow as tf

!pip install ipdb
device = torch.device("cuda")
model.cuda()
total_t0 = time.time()
model = model.to(device)

def format_time(elapsed):
    return str(datetime.timedelta(seconds=int(round((elapsed)))))
training_stats = []

for epoch_i in range(0, epochs):

    # ========================================
    #               Training
    # ========================================

    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
    print('Training...')

    t0 = time.time()

    total_train_loss = 0

    model.train()

    for step, batch in enumerate(train_dataloader):
        # cc = batch.copy()
        # labels = []
        # for en, ex in enumerate(cc[0]):
        #   import ipdb;ipdb.set_trace()
        #   ind_29 = (ex == 29).nonzero(as_tuple=True)
        #   ind_27 = (ex == 27).nonzero(as_tuple=True)
        #   batch[0][en] = cc[0][en][ind_29[0][1]+1:ind_27[0][2]]
        #   batch[1][en] = cc[1][en][ind_29[0][1]+1:ind_27[0][2]]
        #   labels.append(cc[0][en][ind_29[0][2]+1:])
        b_input_ids = batch[0].to(device)
        b_labels = batch[0].to(device)
        b_masks = batch[1].to(device)
        model.zero_grad()        

        outputs = model(  b_input_ids,
                          labels=b_labels, 
                          attention_mask = b_masks,
                          token_type_ids=None
                        )

        loss = outputs[0]  

        batch_loss = loss.item()
        total_train_loss += batch_loss

        # Get sample every x batches.
        if step % sample_every == 0 and not step == 0:

            elapsed = format_time(time.time() - t0)
            print('  Batch {:>5,}  of  {:>5,}. Loss: {:>5,}.   Elapsed: {:}.'.format(step, len(train_dataloader), batch_loss, elapsed))

            model.eval()

            sample_outputs = model.generate(
                                    bos_token_id=random.randint(1,30000),
                                    do_sample=True,   
                                    top_k=50, 
                                    max_length = 200,
                                    top_p=0.95, 
                                    num_return_sequences=1
                                )
            for i, sample_output in enumerate(sample_outputs):
                  print("{}: {}".format(i, tokenizer.decode(sample_output, skip_special_tokens=True)))
            
            model.train()

        loss.backward()

        optimizer.step()

        scheduler.step()

    # average loss over all of the batches.
    avg_train_loss = total_train_loss / len(train_dataloader)       
    
    training_time = format_time(time.time() - t0)

    print("")
    print("  Average training loss: {0:.2f}".format(avg_train_loss))
    print("  Training epoch took: {:}".format(training_time))
        
    # ========================================
    #               Validation
    # ========================================
    '''
    print("")
    print("Running Validation...")

    t0 = time.time()

    model.eval()

    total_eval_loss = 0
    nb_eval_steps = 0

    # Evaluate data for one epoch
    for batch in validation_dataloader:
        input_ids, masks, output_ids, output = preprocess_val_dataset(batch)
        #b_input_ids = batch[0].to(device)
        b_input_ids = input_ids.to(device)
        #b_labels = batch[0].to(device)
        b_labels = input_ids.to(device)
        #b_masks = batch[1].to(device)
        b_masks = masks.to(device)
        #print(f"DEBA: {b_labels}")
        #print(tokenizer.decode(b_input_ids))
        
        with torch.no_grad():        

            outputs  = model(b_input_ids, 
#                            token_type_ids=None, 
                             attention_mask = b_masks,
                            labels=b_labels)
          
            loss = outputs[0]  
            
        batch_loss = loss.item()
        total_eval_loss += batch_loss        
    '''
    total_eval_loss = total_train_loss
    avg_val_loss = total_eval_loss / len(validation_dataloader)

    validation_time = format_time(time.time() - t0)    

    print("  Validation Loss: {0:.2f}".format(avg_val_loss))
    print("  Validation took: {:}".format(validation_time))

    # Record all statistics from this epoch.
    training_stats.append(
        {
            'epoch': epoch_i + 1,
            'Training Loss': avg_train_loss,
            'Valid. Loss': avg_val_loss,
            'Training Time': training_time,
            'Validation Time': validation_time
        }
    )

print("")
print("Training complete!")
print("Total training took {:} (h:mm:ss)".format(format_time(time.time()-total_t0)))

     |████████████████████████████████| 793 kB 22.1 MB/s 
     |████████████████████████████████| 381 kB 65.8 MB/s 
  Created wheel for ipdb: filename=ipdb-0.13.9-py3-none-any.whl size=11648 sha256=bd4dec5fc9d67841b1eac657fc4de9b5fe3c98391a6be991f9255fd856767cf5
  Stored in directory: /root/.cache/pip/wheels/65/cd/cc/aaf92acae337a28fdd2aa4d632196a59745c8c39f76eaeed01
Successfully built ipdb
  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 1.0.18
    Uninstalling prompt-toolkit-1.0.18:
      Successfully uninstalled prompt-toolkit-1.0.18
  Attempting uninstall: ipython
    Found existing installation: ipython 5.5.0
    Uninstalling ipython-5.5.0:
      Successfully uninstalled ipython-5.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-console 5.2.0 requires prompt-toolkit<2.0.0,>=1.0.0, but you have prompt-toolkit


======== Epoch 1 / 5 ========
Training...

  Average training loss: 8.15
  Training epoch took: 0:00:48
  Validation Loss: 18.95
  Validation took: 0:00:48

======== Epoch 2 / 5 ========
Training...

  Average training loss: 2.18
  Training epoch took: 0:00:51
  Validation Loss: 5.08
  Validation took: 0:00:51

======== Epoch 3 / 5 ========
Training...

  Average training loss: 1.64
  Training epoch took: 0:00:52
  Validation Loss: 3.81
  Validation took: 0:00:52

======== Epoch 4 / 5 ========
Training...

  Average training loss: 1.24
  Training epoch took: 0:00:52
  Validation Loss: 2.88
  Validation took: 0:00:52

======== Epoch 5 / 5 ========
Training...

  Average training loss: 0.99
  Training epoch took: 0:00:52
  Validation Loss: 2.31
  Validation took: 0:00:52

Training complete!
Total training took 0:04:14 (h:mm:ss)


In [ ]:
model.eval()

prompt = "<|BOS|>we live in solar system<|SEP|> It has nine planets <|SEP|>"

generated = torch.tensor(tokenizer.encode(prompt)).unsqueeze(0)
generated = generated.to(device)

print(generated)

sample_outputs = model.generate(
                                generated, 
                                #bos_token_id=random.randint(1,30000),
                                do_sample=True,
                                no_repeat_ngram_size=2,  
                                top_k=5, 
                                max_length = 1000,
                                top_p=0.9, 
                                num_return_sequences=3
                                )
for i, sample_output in enumerate(sample_outputs):
  print("{}: {}\n\n".format(i, tokenizer.decode(sample_output, skip_special_tokens=True)))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[50257,   732,  2107,   287,  6591,  1080,    27,    91,  5188,    47,
            91,    29,   632,   468,  5193, 14705,  1279,    91,  5188,    47,
            91,    29]], device='cuda:0')
0: we live in solar system<|SEP|> It has nine planets <|SEP|>The novel begins at the turn of the 20th century. The first book, written by William Tuning and Michael Ardan, tells the remarkable story of a space ship which was built almost immediately after the first lunar landing. In the aftermath of their maiden voyage, the ship's maiden passengers—Mars, a dying planet, and their children—were killed by an accident and stranded for several hundred light years in a desert.
The story ends when the spaceship is recaptured by the hostile natives of Tars Tarkas, who have taken over their world. There they welcomed the newly renamed Nereids, descendants of an old civilization that once dominated the Solar System. They welcomed by a number of Nokoth natives, including a young prince named Nog. A 

In [ ]:
!pip install rouge/requirements.txt
!pip install rouge-score
from rouge_score import rouge_scorer
rouge_1 = {}
rouge_1["precision"] = []
rouge_1["recall"] = []
rouge_1["fmeasure"] = []

rouge_L = {}
rouge_L["precision"] = []
rouge_L["recall"] = []
rouge_L["fmeasure"] = []


for batch in validation_dataloader:
    input_ids, masks, output_ids, ref_story, prompt = preprocess_val_dataset(batch)
    #b_input_ids = batch[0].to(device)
    b_input_ids = input_ids.to(device)
    #b_labels = batch[0].to(device)
    b_labels = input_ids.to(device)
    #b_masks = batch[1].to(device)
    b_masks = masks.to(device)
    #print(f"DEBA: {b_labels}")
    #print(tokenizer.decode(b_input_ids))
  
    #prompt = input_ids

    generated = torch.tensor(tokenizer.encode(prompt)).unsqueeze(0)
    generated = generated.to(device)

    print(generated)

    sample_outputs = model.generate(
                                    generated, 
                                    #bos_token_id=random.randint(1,30000),
                                    do_sample=True,
                                    no_repeat_ngram_size=2,  
                                    top_k=5, 
                                    max_length = 1000,
                                    top_p=0.9, 
                                    num_return_sequences=3
                                    )
    
    for i, sample_output in enumerate(sample_outputs):
      s =  tokenizer.decode(sample_output, skip_special_tokens=True)
      print(s)
      scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
      scores = scorer.score(s, ref_story)
      print(scores)
      rouge_1["precision"].append(scores["rouge1"][0])
      rouge_1["recall"].append(scores["rouge1"][1])
      rouge_1["fmeasure"].append(scores["rouge1"][2])

      rouge_L["precision"].append(scores["rougeL"][0])
      rouge_L["recall"].append(scores["rougeL"][1])
      rouge_L["fmeasure"].append(scores["rougeL"][2])
      print("************************************")

print("*********ROUGE-1************")
avg_pre = sum(rouge_1["precision"])/len(rouge_1["precision"])
avg_recall = sum(rouge_1["recall"])/len(rouge_1["recall"])
avg_fmeasure = avg_pre = sum(rouge_1["fmeasure"])/len(rouge_1["fmeasure"])
print("avg_acc: "+str(avg_pre))
print("avg_recall: "+str(avg_recall))
print("avg_fmeasure: "+str(avg_fmeasure))

print("*********ROUGE-L************")
avg_pre = sum(rouge_L["precision"])/len(rouge_L["precision"])
avg_recall = sum(rouge_L["recall"])/len(rouge_L["recall"])
avg_fmeasure = avg_pre = sum(rouge_L["fmeasure"])/len(rouge_L["fmeasure"])
print("avg_acc: "+str(avg_pre))
print("avg_recall: "+str(avg_recall))
print("avg_fmeasure: "+str(avg_fmeasure))
      

ERROR: Invalid requirement: 'rouge/requirements.txt'
Hint: It looks like a path. File 'rouge/requirements.txt' does not exist.


Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[50257,   220, 50257,   383, 11397, 10318,   690,    27,    91,  5188,
            47,    91,    29,  7785,   699,   584,  9180,  1220,  8982,   262,
          8806,  6253, 11661, 13069,  3653, 17372,  5328, 31707, 27406,    12,
            88,   418,   407, 34579,  4678, 12524,  4894, 16343,   284,  1842,
           257,  9233,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  The Planet Savers<|SEP|>various other Jay / Jason the personality doctor volunteers Trailmen fever hypnosis yo-yos not External skills hostile heat nest to love a secondary<|SEP|>The planet Saverns has been retconned by Jason Allison, a ruthless advertising executive who knows his place in the world and can spot a flaw in its advertising tactics. Jason has hired an undercover FBI agent to infiltrate the planet's political and economic life, and has installed a sophisticated advertising program to fool its unsuspecting consumers. In this guise, Jason is a regular guy who volunteers his

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.23887973640856672, recall=0.19594594594594594, fmeasure=0.21529324424647364), 'rougeL': Score(precision=0.09884678747940692, recall=0.08108108108108109, fmeasure=0.08908685968819599)}
************************************
tensor([[50257,   220, 50257,   383,  3878, 18329,  6896,    27,    91,  5188,
            47,    91,    29, 28116,   282,  2585,  1812,  1956,  1049,  7630,
          5417,  1241,  1660,   262, 26824,  1017,  1191,   257,   649, 37874,
          3450,   661,   636,  4025,  8046,    27,    91,  5188,    47,    91,
            29]], device='cuda:0')
  The Great Nebraska Sea<|SEP|>several states State land great profit sea level water the governors slivers a new inland nature people part larger fault<|SEP|>The story begins with the discovery of a submerged land far larger than the Mississippi, called the Great Nebes. The story mainly takes place in the present-day West Indies, whereof the great bulk of the world was once located. It is a land

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.35478806907378335, recall=0.2864385297845374, fmeasure=0.3169705469845722), 'rougeL': Score(precision=0.14599686028257458, recall=0.11787072243346007, fmeasure=0.13043478260869565)}
************************************
tensor([[50257,   220, 50257,  1649,   262, 19498,  5723,   370,  1124,    27,
            91,  5188,    47,    91,    29,  1102,  8534,  3236,  5129,  6712,
          3259,  1418, 13363,  3259,  3098,    12,   958,  3323,  6541, 31723,
          9312,  3819,  1748,   407,  7368,  8716,    82,  2831, 11520, 19401,
         17390,  2344,    76,  2171,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  When the Sleeper Wakes<|SEP|>confront huge wealth institutions workers untrained workers anti-aircraft guns politic entity Other city not specified joys industry Graham airplane accidents windmills<|SEP|>The story begins in New York City, where a young man named Martin "Storm" Spencer is developing a love interest in aeroplanes

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.5697478991596638, recall=0.42111801242236024, fmeasure=0.48428571428571426), 'rougeL': Score(precision=0.1899159663865546, recall=0.14037267080745341, fmeasure=0.16142857142857142)}
************************************
tensor([[50257,   220, 50257,   383, 13094,    27,    91,  5188,    47,    91,
            29,  7344,   641,   407, 18149,   262, 23723,   317,    12,  8413,
           391,  8855,   383,   649,   530,   262,  3025,    11,  3025,  3025,
            11,  3025,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  The Players<|SEP|>aliens not nonsense the philosopher A-Remain adventure The new one the whose, whose whose, whose<|SEP|>Professor Pierre Aronnax explores a philosophical dead end of a long and tiring search for answers. Canadian whaler and master harpoonist Ned Land is puzzled by a passage in the novel that appears to have been left behind by an old enemy. Aronsnakes and his companions are puzzled as to where the pass

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.02351313969571231, recall=0.02309782608695652, fmeasure=0.023303632625085675), 'rougeL': Score(precision=0.017980636237897647, recall=0.017663043478260868, fmeasure=0.017820424948594923)}
************************************
tensor([[50257,   220, 50257, 21939,  1044,    25,   317, 36555,   286,  4650,
         41265,   357, 21478,   436,  4111,     8,    27,    91,  5188,    47,
            91,    29,  3605,   530,  2546,  2440,  3234,  7325,  4333,   257,
         10467, 15793,   262,  2972,  3146,  5389,  1864,   284,   543,  1466,
          7683,  4930, 38445,  5538,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  Flatland: A Romance of Many Dimensions (Illustrated)<|SEP|>new one size higher race creative Power a Third dimension the various numbers sides according to which women Three Two geometric figures<|SEP|>The story begins with a young man named Dane, who has a dream in which he is to travel in three dimensions, one for himse

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4703891708967851, recall=0.38082191780821917, fmeasure=0.42089326267978805), 'rougeL': Score(precision=0.1793570219966159, recall=0.14520547945205478, fmeasure=0.16048448145344432)}
************************************
tensor([[50257,   220, 50257,   383, 28586, 11397,    27,    91,  5188,    47,
            91,    29,    70,   328,  5109,  6129,   373,   862, 10620, 25972,
          3352, 19435,   262,  2546,   286,   257, 17481, 27842,  4695, 25321,
           262,  1675,  3953, 33712,  9441,  5384,  1204,   257,   340,  6265,
         40663,    27,    91,  5188,    47,    91,    29]], device='cuda:0')
  The Forgotten Planet<|SEP|>gigantic fly wasps sizes chickens plans insects the size of a wolf ants animals descendants the To measure microbes survival humans life a it broke spaceship<|SEP|>The story opens in the jungles far to the north of Mexico. The protagonist is an elderly, rural man from Tlaxalt, Arizona. He is bothered by an unseen flying machine 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.08534850640113797, recall=0.07751937984496124, fmeasure=0.08124576844955991), 'rougeL': Score(precision=0.049786628733997154, recall=0.04521963824289406, fmeasure=0.04739336492890995)}
************************************
tensor([[50257,   220, 50257, 29496, 18489,   371,  1460,   262, 12723, 11397,
            27,    91,  5188,    47,    91,    29,    69,  1480,   540,  2587,
           987,    12, 15271, 26390,  5899, 41899,  1505,   779,   262, 27460,
         10999, 40343,   281,  1630,   257, 11000,     8, 19090,    13,  5855,
            49,   541,  4943,  6554,  2272,    12,  5146,  7548,    27,    91,
          5188,    47,    91,    29]], device='cuda:0')
  Rip Foster Rides the Gray Planet<|SEP|>fissionable material inter-service rivalry pure thorium use the asteroid belt Governments an control a Marine) Lt. ("Rip") agents space-going equivalent<|SEP|>Roddy McDowall is the lone survivor of a space battle in space. He is captured by spacefarers in a

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.09024745269286755, recall=0.08794326241134752, fmeasure=0.08908045977011494), 'rougeL': Score(precision=0.043668122270742356, recall=0.0425531914893617, fmeasure=0.04310344827586207)}
************************************
tensor([[50257,   220, 50257,   383,  2805,   278,  3461,   684,    27,    91,
          5188,    47,    91,    29,  4491,   684,  2272,  3067, 12267, 11613,
         10815, 28063,  1956, 24627,  1281, 27761, 36956, 27503,  3725,  7040,
           262, 27523,  3265,  1917,  1588,  4172,    27,    91,  5188,    47,
            91,    29]], device='cuda:0')
  The Marching Morons<|SEP|>morons space travel Nazi propaganda tactics worthless land fraudulent postcards hormonal contraception knowledge deaths the impending population problem large families<|SEP|>The March of Dimes is set to begin onThe plot of the story begins on September 1, 1933, with a coded message informing the reader that the plot has been completed, and ending with the death 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.32305194805194803, recall=0.2515802781289507, fmeasure=0.2828713574982231), 'rougeL': Score(precision=0.12824675324675325, recall=0.09987357774968394, fmeasure=0.1122956645344705)}
************************************
tensor([[50257,   220, 50257,   383,  5648, 11451, 22732,    27,    91,  5188,
            47,    91,    29,  9937,  8468, 11354, 11683,  5509,   491, 14125,
          6049,  1280, 14129, 30671,  3006,   584, 12782,  1811, 33777, 17025,
          7150,  1528,  5187,    65,  1834, 10663,    12, 10734, 21304,    27,
            91,  5188,    47,    91,    29]], device='cuda:0')
  The Dunwich Horror<|SEP|>mad unusual ferocity tree trunks severe open wounds inhabited areas other libraries several policemen cattle trees days Wilburs semi-human corpse<|SEP|>Police investigate a house fire that destroyed a minuscule part of the Dunfellers' library, but the mysterious fire spreads rapidly and rapidly through the neighborhood, causing fear and panic. T

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


  The Dunwich Horror<|SEP|>mad unusual ferocity tree trunks severe open wounds inhabited areas other libraries several policemen cattle trees days Wilburs semi-human corpse<|SEP|>Police investigate the mysterious "Great Dane's Whuffie" tree-gutter demon-ape, which some suggest to be a giant monster. The monster, described only by its grotesque forms as a barrel-like creature with wounds. Wilbur's trunk is found in a barn, about 2,500 years before its destruction. He was the son of a Renunciate priest and his faithful servant. As a boy, Wilbert was sent to a cult where he was made to undergo the same painful and apparently uncontrollable abuse as his father. Frightened, horrified, he walks out of the room, and the apparition vanishes. Later, the family finds a note written in the brush by Wilters in which the note reads:

Wilbur has heard of some strange creatures who roam the woods, some of them ugly and ugly, but they do not appear human. They only appear in small, yellow, sometimes m

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.17638483965014579, recall=0.15125, fmeasure=0.16285329744279947), 'rougeL': Score(precision=0.08454810495626822, recall=0.0725, fmeasure=0.07806191117092867)}
************************************
tensor([[50257,   220, 50257,   383, 19821,  9561,  4687,    27,    91,  5188,
            47,    91,    29,  1169, 11198,  4332, 24242,   749,  2274,  6843,
         13521,   307,  3748,  2420, 15425,   257,  2910, 21419,   257,  4430,
          5797,  1320,   995,  5093,   383,    27,    91,  5188,    47,    91,
            29]], device='cuda:0')
  The Door Through Space<|SEP|>the Double Press differs most recent chapter 1979 be unique text villages a blood feud a intelligence agent That world north The<|SEP|>The novel concerns the life of a small town in the Soviet Union. The protagonist is a politician, who has a dream to establish a world order based on his own experience in politics. He works in a Soviet-style "closed-door society" and has an idea for how to 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.048409405255878286, recall=0.04315659679408138, fmeasure=0.04563233376792699), 'rougeL': Score(precision=0.034578146611341634, recall=0.030826140567200986, fmeasure=0.03259452411994785)}
************************************
tensor([[50257,   220, 50257, 49034,   960,  1731,  1129,   317,    13,    35,
         29847,    91,  5188,    47,    91,    29,  6395,  4097,  8976,  7937,
           649,   530, 10815,  3242,  1063,  9958, 12896, 18446,   262,   257,
          4472,  6193,  2972,  1528,  2460,  2910,  3807, 11389,    27,    91,
          5188,    47,    91,    29]], device='cuda:0')
  Armageddon—2419 A.D.<|SEP|>Other band rival ships new one tactics Offices abandoned Coal mines the a enemy weather various days friends blood movie serial<|SEP|>In the distant future a band of renegade scientists, including Dick Jarvis and Michael Ardan, set out to find and destroy the planet Helium. The group found it buried in the ice and were surprised to come face to

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4838160136286201, recall=0.3722149410222805, fmeasure=0.4207407407407407), 'rougeL': Score(precision=0.18568994889267462, recall=0.14285714285714285, fmeasure=0.1614814814814815)}
************************************
tensor([[50257,   220, 50257, 21026,   286, 13596,   397,   276,  5031,    27,
            91,  5188,    47,    91,    29,   272,  8756,   995,   262,  2003,
           257,  1048,   383,  5337,   508,    27,    91,  5188,    47,    91,
            29]], device='cuda:0')
  Falcons of Narabedla<|SEP|>an alien world the future a person The novel who<|SEP|>The novel concerns the adventures of the protagonists, usually played by William Tuning, a sailor on a ship with a number of other passengers, during the year 1866. The ship's communication system was sabotaged and the captain, Jameson J. Harper, attempts to contact the alien Kulan Teth, the world's lone survivor of an alien attack. However, Tith's technology is inferior to that of its human-lik

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.024691358024691357, recall=0.022988505747126436, fmeasure=0.02380952380952381), 'rougeL': Score(precision=0.019204389574759947, recall=0.017879948914431672, fmeasure=0.018518518518518517)}
************************************
tensor([[50257,   220, 50257,   383, 19148,   291,    27,    91,  5188,    47,
            91,    29, 14480,  7674,  3819, 14807,  6486, 40471,  8976, 46026,
          4097,  4800,  1637, 16425,  5635,  5735, 16786,  6193, 24329,   262,
          2717,  1479,  1714,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  The Syndic<|SEP|>government territory Other islands lie detectors rival delinquent band protection money authentic powers telepathy weather exile the federal free sex<|SEP|>The story opens in the jungles of South America. The protagonists are Travis Fox, a young settler who is sent on an expedition to retrieve a coveted "telepathic tip" from an old settlerman who recorded his adventures in South American 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.21796759941089838, recall=0.19973009446693657, fmeasure=0.2084507042253521), 'rougeL': Score(precision=0.08836524300441827, recall=0.08097165991902834, fmeasure=0.08450704225352113)}
************************************
tensor([[50257,   220, 50257,   383,  4380,   286,   262,  2619, 16291,    27,
            91,  5188,    47,    91,    29,   301,   403,  1494,  3817,  5718,
           364,   416, 31634,  2180, 37071,   314,  2865,   952,  6300, 40255,
          6937,   679, 18240,   284,  1842,  3687,  2106, 34254, 26884,   126,
           123, 23141, 35906,  5358, 10802,   422,  7858, 15776,  1393,    27,
            91,  5188,    47,    91,    29]], device='cuda:0')
  The People of the Black Circle<|SEP|>stun kill mountaineers by Conan previous mythical Iborio versions equivalents constant He stole to love East history Bj�rn conflict confusion from turanium interest<|SEP|>The story opens in London in 1897, and Conan, the mad scientist, is heading for t

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.5268199233716475, recall=0.34942820838627703, fmeasure=0.4201680672268908), 'rougeL': Score(precision=0.20114942528735633, recall=0.13341804320203304, fmeasure=0.16042780748663102)}
************************************
tensor([[50257,   220, 50257, 12010,   286,  4687,    27,    91,  5188,    47,
            91,    29,   464, 14807,   422,   262,   257, 24659,  1440, 10281,
          8855,  1320,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  Islands of Space<|SEP|>The islands from the a continuation four heroes adventure That<|SEP|>Captain Nemo is heading to the southern hemisphere to find and destroy a downed U.S. Navy frigate, USS Susquehanna. Nemos motivation is implied to be both a desire for revenge and revenge on the UPC. When the ship is attacked by pirates, Nemoi and his men hijack the aircraft, ramming it just below the waterline, sinking it into the bottom of the sea. They are recaptured by a coalition of pirates and brough

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.02620689655172414, recall=0.02526595744680851, fmeasure=0.025727826675693975), 'rougeL': Score(precision=0.022068965517241378, recall=0.02127659574468085, fmeasure=0.02166553825321598)}
************************************
tensor([[50257,   220, 50257,   317, 15120,   656,   262, 19614,   286,   262,
          3668,    27,    91,  5188,    47,    91,    29, 18217,  1473, 30668,
          1063,   427,  5286,  3641,   708,   654,  8758,  6582, 17288,   375,
           684,  4273, 41301,  7150,  3638,  6175, 28520,  2972,  5654, 10946,
         19435,   885,    76,  4650,  4608,  2972,    27,    91,  5188,    47,
            91,    29]], device='cuda:0')
  A Journey into the Interior of the Earth<|SEP|>silently rejoices shaded center attings Kentrum mastodons petrified trees touch giant mushroom various scientific theories insects kem Many miles various<|SEP|>In this new adventure the main character, Kent, an astronaut named Jim, awakens in the body of a Beake

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4523809523809524, recall=0.26898326898326896, fmeasure=0.33736884584342214), 'rougeL': Score(precision=0.18831168831168832, recall=0.11196911196911197, fmeasure=0.1404358353510896)}
************************************
  A Journey into the Interior of the Earth<|SEP|>silently rejoices shaded center attings Kentrum mastodons petrified trees touch giant mushroom various scientific theories insects kem Many miles various<|SEP|>Professor Kent Rainsford, a London based physicist and narrator of "Nightmare Planet", a scientific experiment in which he explains that he has been traveling for eleven years, and that his last stop, Auburn, New York, is the world's capitol. Raining the forces of evil from beneath the city, he creates a vast, immaterial, translucent globe of pure gold and uses it to guide his spaceship through a series of seemingly bizarre and apparently inexplicable geometric forms. He travels back in time, encountering bizarre geometric shapes, but he

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.2887864823348694, recall=0.2422680412371134, fmeasure=0.263489838822705), 'rougeL': Score(precision=0.11213517665130568, recall=0.09407216494845361, fmeasure=0.10231254379817799)}
************************************
tensor([[50257,   220, 50257,  3574,   262,  3668,   284,   262,  6869,    26,
           290,    11, 10485,   262,  6869,    27,    91,  5188,    47,    91,
            29,    64,  1864,   284,  8824, 26049, 14180,  8500, 17416,   262,
          6175,  2272, 16790, 31093,  8372, 33169,  1441, 10492,   640, 27465,
         10252, 16765,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  From the Earth to the Moon; and, Round the Moon<|SEP|>a according to moon Opera cups neutral attraction the giant space pistol moons southern hemisphere return bullet time geographical remarks calculations<|SEP|>The story begins in the town of Kapuskasing, Alaska.  Although the story takes place several hundred years prior to its publication, 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4410828025477707, recall=0.3574193548387097, fmeasure=0.39486813970064155), 'rougeL': Score(precision=0.18630573248407642, recall=0.15096774193548387, fmeasure=0.16678545972915182)}
************************************
tensor([[50257,   220, 50257,   569, 36038, 11397,    27,    91,  5188,    47,
            91,    29, 21834, 11621,  1081,  8182,   447,   247,    82,  1917,
          5536,   745, 17892, 18348,  1671, 18526,   447,   247,    82,   551,
            76,   414,   281, 48851,  6920,  6339,   509,  5183,  4914,   447,
           247,    82,  4923,   277, 32837,   257,  3621,  5897,  1057,   317,
            27,    91,  5188,    47,    91,    29]], device='cuda:0')
  Voodoo Planet<|SEP|>many worlds Asaki’s problem magic poachers Lumbrilo’s enmity an interstellar mail route Khatka’s dangerous fauna a nice quiet run A<|SEP|>The story begins on May 15, 1903 in the jungles of South America. A passing spaceship takes a strange yellowish-blue light from

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.2495921696574225, recall=0.2125, fmeasure=0.22955738934733683), 'rougeL': Score(precision=0.09787928221859707, recall=0.08333333333333333, fmeasure=0.09002250562640658)}
************************************
tensor([[50257,   220, 50257, 23405,  2907, 11397,    27,    91,  5188,    47,
            91,    29,  6270,  1976,    50,   430,  1648, 38812,  8698,  6868,
         16569,  2219, 25542, 11353,  6541,  6844, 12954,  1332,  3516,  1090,
           494,   257, 19159,    88,  2277,  2272, 34870,    27,    91,  5188,
            47,    91,    29]], device='cuda:0')
  Lone Star Planet<|SEP|>law zSrauff expulsion covers native costume common killers automatic guns dogs criminals test guy curie a stealthy hit space humanoid<|SEP|>The novel concerns Patricia Lane, who has been sent on an emergency trip to the planet Sari from the novel's first half. Her trip takes her to a planet she knows and the locals as Barsoom. She finds a young settler named Tolkemec, a d

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4292929292929293, recall=0.31954887218045114, fmeasure=0.36637931034482757), 'rougeL': Score(precision=0.15656565656565657, recall=0.11654135338345864, fmeasure=0.1336206896551724)}
************************************
tensor([[50257,   220, 50257, 11397,   286,   262,  5245,  2817,    27,    91,
          5188,    47,    91,    29,  1326,  1039, 22843,  2501, 12134,   257,
          5440,  3094,  2168,  5307, 42960,   662,    12,  1791,   425,  4523,
          5587,   262, 10326, 10325,   584,  5384, 29272,   890,  4692,  7374,
            27,    91,  5188,    47,    91,    29]], device='cuda:0')
  Planet of the Damned<|SEP|>meets cobalt bombs a planet wide series symbiosis pre-emptive nuclear strike the desert arrival other humans neighbouring long cold winter<|SEP|>During the year 1866, a band of renegade scientists, led by Dr. Loddy McDowall, arrive on an abandoned planet, and begin torturing and destroying its inhabitants. The group is initially led in

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.20508982035928144, recall=0.16585956416464892, fmeasure=0.18340026773761714), 'rougeL': Score(precision=0.09730538922155689, recall=0.07869249394673124, fmeasure=0.08701472556894244)}
************************************
tensor([[50257,   220, 50257,  2907, 18889,    27,    91,  5188,    47,    91,
            29,   272,  9958,  1748,   262, 19467,   257, 20484, 48851,  5474,
          1290,  8272,  5735, 38829, 24248,   511, 45086, 10223,  6147, 11760,
          2800,  4844,  2272,  5384,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  Star Born<|SEP|>an abandoned city the forbidden a ruined interstellar flight faraway telepathic relay their hyperspace metal bands contact none space humans<|SEP|>The novel concerns the adventures of Alan Donnell, the ex-con who is stranded on the moon, after a long absence from Earth. Alan is taken by Major John Kelgarries and brought back to the surface world of Tellus, where he meets a band of spacef

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.5164473684210527, recall=0.39103362391033625, fmeasure=0.445074415308292), 'rougeL': Score(precision=0.17763157894736842, recall=0.13449564134495642, fmeasure=0.15308291991495393)}
************************************
tensor([[50257,   220, 50257,   383,  6869, 19850,    27,    91,  5188,    47,
            91,    29, 48477,  3492, 11728,  2092,   284,   257, 21264,  4693,
          3894,   284, 28615,  7477,    68, 22521,  1111,   286,   606,  1049,
           575,   884,  6193,   284,  1842,   262,   584,  1466, 12799,  1692,
          7030,  1869,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  The Moon Pool<|SEP|>Evil ready sacrifice similar to a frog species Well to prevail OKeefe both of them great Y such weather to love the other women essence human waste Man<|SEP|>It is the year 1999. A young man named Jack is stranded in a swamp, and his family are stranded on the coast after a long, harrowing ordeal. They are rescued by a boa

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.2775193798449612, recall=0.23186528497409326, fmeasure=0.2526464361326746), 'rougeL': Score(precision=0.10852713178294573, recall=0.09067357512953368, fmeasure=0.09880028228652081)}
************************************
tensor([[50257,   220, 50257,   383, 19498,  5723,  5851,  1124,    27,    91,
          5188,    47,    91,    29,  1102,  8534,    82,  3236,  5129,  6712,
         16847,   791, 44885,  3259,  3098,    12,   958,  3323,  6541,  1964,
         12066,   584,  4736, 29547,  8716,    82,  2831, 11520,    82,  9551,
         20106,  1531, 17616,  2344,    12,    76,  2171,    27,    91,  5188,
            47,    91,    29]], device='cuda:0')
  The Sleeper Awakes<|SEP|>confronts huge wealth institutions Workers Unskilled workers anti-aircraft guns political entities other cities unspecified joys industry Grahams aeroplane crashes wind-mills<|SEP|>The story opens in the Soviet Union. A group of businessmen and businessmen decide to build a nuclea

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.6030405405405406, recall=0.4451371571072319, fmeasure=0.5121951219512195), 'rougeL': Score(precision=0.19087837837837837, recall=0.14089775561097256, fmeasure=0.16212338593974177)}
************************************
tensor([[50257,   220, 50257, 31428,    27,    91,  5188,    47,    91,    29,
         19734,  1633,  5006,   749,  9473, 27324,  3348,  5584, 12129,   678,
           400,  4289,  2354, 30794,   262,   584,  3435, 15616,  1466,   640,
          2666,    27,    91,  5188,    47,    91,    29]], device='cuda:0')
  Equality<|SEP|>private air cars most papers strengthened paper motor capitalism 19th century outside museums the other characters Looking women time leave<|SEP|>The novel opens with the heroine, Dorothy Vaneman, being blown up in the explosion of the atomic bombs that devastated Manhattan on September 11, Manhattan. Dorothy had been traveling in her car when it began to blow up. The explosion caused extensive destruction, and Dorothy

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.3705426356589147, recall=0.3144736842105263, fmeasure=0.3402135231316726), 'rougeL': Score(precision=0.12868217054263567, recall=0.10921052631578948, fmeasure=0.11814946619217083)}
************************************
tensor([[50257,   220, 50257,  3334,  1322,   287,   367,  2530,    27,    91,
          5188,    47,    91,    29, 10823, 10524,  3338, 20089,  5735,  6978,
            82,   661,  6066,  2208,  3653, 15024,   364,  1243,  3294,  7110,
          6615,   262, 14112, 25035, 42859, 20282,    82, 21189,   257,  7104,
         12763,  1430,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  Highways in Hiding<|SEP|>rock sorts safehouses telepaths people thoughts supermen espers things multiple plotlines the infected limb Mekstroms toe a hidden highway program<|SEP|>The plot focuses on the protagonist, Tyler Tyler, an engineer in the Radiation Lab who mysteriously disappears whilst on a trip to the remote town of Kapuskasing. Tyl

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.1567489114658926, recall=0.14535666218034993, fmeasure=0.15083798882681562), 'rougeL': Score(precision=0.08127721335268505, recall=0.07537012113055182, fmeasure=0.0782122905027933)}
************************************
tensor([[50257,   220, 50257, 31816, 34900,    27,    91,  5188,    47,    91,
            29,  1169,   749,  2274,  1178,  3026,   465,  3520,   314, 13818,
          1862, 16713,  7451,   257,  2456,  6035,   274,  7606,    11, 17838,
         45993, 20052,  4963,  3835,  1103,   220,  9412,   257,    27,    91,
          5188,    47,    91,    29]], device='cuda:0')
  Omnilingual<|SEP|>the most recent few civil his remain I laughed young archaeologist a words Danes competitive, spotlight seeker teammate documents books real  discovery a<|SEP|>The novel concerns a young man who has been ridiculed or disowned by archaeologists for his lack of curiosity. When archaeology is underway in New York City, Professor Pierre Aronnax, a French adventu

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.09455587392550144, recall=0.08188585607940446, fmeasure=0.08776595744680851), 'rougeL': Score(precision=0.050143266475644696, recall=0.043424317617866005, fmeasure=0.04654255319148935)}
************************************
tensor([[50257,   220, 50257,   383,  5274,  1148, 42914,    27,    91,  5188,
            47,    91,    29, 22975,  4159,  7588, 33013,  3783,   407,  3236,
         32271,  5920, 12989,  4608,   465,   649,   530,   995,   262, 11621,
         20494, 13851,   281, 11949,   257,    27,    91,  5188,    47,    91,
            29]], device='cuda:0')
  The Sky Is Falling<|SEP|>Magic minor lights physicist science not huge heavenly bodies trillion miles his new one world the worlds Paradise Computer an engineer a<|SEP|>The story takes place in a distant future, in which the sun is slowly moving toward a point seven miles per hour in diameter. The sun has made a series of changes over the millennia, but now it is moving towards the point at w

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.10460251046025104, recall=0.09702457956015524, fmeasure=0.1006711409395973), 'rougeL': Score(precision=0.0599721059972106, recall=0.055627425614489, fmeasure=0.05771812080536912)}
************************************
tensor([[50257,   220, 50257,   383,   370, 11608, 38484,  1868,    27,    91,
          5188,    47,    91,    29, 26093,  5895,  1231, 30476, 16790,  1310,
          2619, 34896, 23315,  7183,  2769,  2272,  1528, 48851,   257, 16195,
         18944,  1029,  1524,   257,  1051,  1657,    27,    91,  5188,    47,
            91,    29]], device='cuda:0')
  The Wailing Asteroid<|SEP|>Radio signs without recoil pistol little Black cubes Cube readers deep space days interstellar a stranger Weapons high school a sign light<|SEP|>The novel begins in the year 1999, with the release of "Nightmare in Space", "Star Trek", and "The Expanse". The novel follows the adventures of a young girl (about 14 or 15) whose discovery is made when a small crashed sp

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4310897435897436, recall=0.3312807881773399, fmeasure=0.3746518105849582), 'rougeL': Score(precision=0.17467948717948717, recall=0.13423645320197045, fmeasure=0.15181058495821725)}
************************************
tensor([[50257,   220, 50257, 31428,    27,    91,  5188,    47,    91,    29,
         19734,  1633,  5006,   262,  3741,  4963, 40479,  3348,   262,  3113,
         12129,   678,  4289,  2354, 30794,   262,  3819,  3435,  4992,  1466,
          6193, 17446,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  Equality<|SEP|>private air cars the majority documents fortified paper the engine capitalism 19 century outside museums the Other characters Research women weather Leave<|SEP|>The story begins in 1844 in London, where Impey and his millionaire sponsor, Simon Delgatty, are investigating reports of a plot by the French government to poison the English public through an effort to undermine the monarchy. In collusion with t

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.34627329192546585, recall=0.3005390835579515, fmeasure=0.3217893217893218), 'rougeL': Score(precision=0.12111801242236025, recall=0.10512129380053908, fmeasure=0.11255411255411255)}
************************************
tensor([[50257,   220, 50257, 17917,    25, 48278,    27,    91,  5188,    47,
            91,    29, 11265,  5384,  2622, 18423,    82,   257,  1762, 13522,
          3708,  9314,   262,  1080,  6591,   649,  2761,   383, 35113,    12,
          2339, 16269,   753, 11970,  6821,  3612,    27,    91,  5188,    47,
            91,    29]], device='cuda:0')
  Address: Centauri<|SEP|>normal humans needed pharmaceuticals a working gravity drive reliable the system solar new problems The butterfly-like aliens incurable injuries thinking<|SEP|>In the year 1866, ships of several nations spot a strange light-years from Earth. A band of "Harnets" (aka "Yuks") from the distant starships "Chronicle of the Law" travel in a spaceship that is traveling at 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.1875, recall=0.17108753315649866, fmeasure=0.17891816920943132), 'rougeL': Score(precision=0.07994186046511628, recall=0.07294429708222812, fmeasure=0.07628294036061026)}
************************************
tensor([[50257,   220, 50257,   362,   347,   371,   657,   362,   347,    27,
            91,  5188,    47,    91,    29, 39748,  2198,  5778,  5863,  7519,
          5830, 20117, 16460,  7007,   356,    71,  1359,  4901, 13794, 18156,
          1204, 17507,  4082, 27244,  2119, 20669, 15055,   912, 35236,  1502,
            27,    91,  5188,    47,    91,    29]], device='cuda:0')
  2 B R 0 2 B<|SEP|>population check accident famous doctors Death deceased hunger requests wehling belief Undefined life expectation birth births room nurses triplets Plague order<|SEP|>The story begins in the asylum on 3rd floor of the World Trade Centre. The asylum's inhabitants are crowded into an open room, perpetually jockeying for position in various scientific and te

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.30483870967741933, recall=0.250996015936255, fmeasure=0.2753095411507648), 'rougeL': Score(precision=0.12096774193548387, recall=0.099601593625498, fmeasure=0.10924981791697014)}
************************************
tensor([[50257,   220, 50257, 18037,   287,   262, 39951,    27,    91,  5188,
            47,    91,    29,   272,  3456, 20073,  6175, 47069,   364,  1450,
         34267,   262, 21196,  3868,   417,   522, 25827,  1204,  7542,   286,
         13125,   290,  3996,    81,  9460,   992, 27516, 40019,  4448, 10251,
           257,    27,    91,  5188,    47,    91,    29]], device='cuda:0')
  Shadows in the Moonlight<|SEP|>ancient ruins giant boulders men wakes the remarkably lifelike statues life Queen of beaten and bedraggled pirates Olivias fears a<|SEP|>Having been kidnapped and held for an expedition to the moon's southern hemisphere, the pirate leader Olmec decides to take his revenge on his old enemy. He is sent on a pirate attack, and soo

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.3813291139240506, recall=0.32219251336898397, fmeasure=0.34927536231884054), 'rougeL': Score(precision=0.14715189873417722, recall=0.12433155080213903, fmeasure=0.13478260869565217)}
************************************
tensor([[50257,   220, 50257,   383, 11165, 13072,    27,    91,  5188,    47,
            91,    29,  8419,  9998,   938,  2911, 17610, 39417,   511, 48744,
         11026,   262,  8713,  4282, 24312,  1363,    12, 47427,   835, 10528,
           326,   508,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  The Ultimate Weapon<|SEP|>Earths last hope Alien invaders their starship fleet the ultimate weapon doomed home-planet way Nothing that who<|SEP|>Alien invaders a native planet devastated by the war between the alien races and their technology. The aliens succeed in destroying the planet, but the natives have not been able to return to their homeworld for several generations.


The story goes:
The natives of planet Ear

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.04419889502762431, recall=0.04071246819338423, fmeasure=0.0423841059602649), 'rougeL': Score(precision=0.027624309392265192, recall=0.02544529262086514, fmeasure=0.02649006622516556)}
************************************
tensor([[50257,   220, 50257,   569,   278,    83,  1465,   293, 12060,   947,
           311,   516, 11732,   337,   364,   851, 13248,    27,    91,  5188,
            47,    91,    29, 25031,  7937, 14101,  3048,   584, 16050,  1204,
          6190, 17219,  2267, 22547,   418, 14052,  1103,  3403, 11561, 22780,
           257, 11428,  5417,  9234,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  Vingt mille Lieues Sous Les Mers — Complete<|SEP|>Professor ships devastating effects other marine life advanced biology research Nemos motivation real conditions commander secrecy a mysterious sea monster<|SEP|>In this novel, Professor ships an experimental antigravity drive that can produce tremendous accelerations, and in 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.629695885509839, recall=0.4577373211963589, fmeasure=0.5301204819277109), 'rougeL': Score(precision=0.22182468694096602, recall=0.16124837451235371, fmeasure=0.18674698795180722)}
************************************
tensor([[50257,   220, 50257, 41671,   422,   262, 22380,    27,    91,  5188,
            47,    91,    29, 16668, 22242, 10281,   383,   286,   257,  3234,
           511,  6370, 19886, 16304,  5337,    27,    91,  5188,    47,    91,
            29]], device='cuda:0')
  Invaders from the Infinite<|SEP|>superdogs heroes The of a race their attempts trio sequel novel<|SEP|>The novel concerns the adventures of the heroes of The Black Company.

The Black Brotherhood is a white-dominated society based on a biological code of honor and conformity. The main character,The Brotherhood of Assassins (also called the Black Council), is an offhand remark made by a member of one of its chapters. He refers to the Brotherhood as a force for evil and a feare

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.031724137931034485, recall=0.029077117572692796, fmeasure=0.030343007915567283), 'rougeL': Score(precision=0.02482758620689655, recall=0.022756005056890013, fmeasure=0.0237467018469657)}
************************************
tensor([[50257,   220, 50257,  5181,   290, 21839,    27,    91,  5188,    47,
            91,    29, 15182,  4133,  1180, 14705, 10620, 12661,  1204,   584,
           736, 39493,  5112,  1402,  6670, 11219, 13135,  3925, 15268,  3211,
         12604,  3614, 14271,  4334,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  Cat and Mouse<|SEP|>available resources different planets sizes intelligent life other backwoods equipment small targets tobacco juice individuals shapes armaments limited ammunition heavy<|SEP|>The story opens in the town ofCat and the Mouse (1948) are two of the most popular children's book series in North America. It was first published in form in 1960 and continues through the 2000s. The first bo

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.3354330708661417, recall=0.3021276595744681, fmeasure=0.31791044776119404), 'rougeL': Score(precision=0.12283464566929134, recall=0.11063829787234042, fmeasure=0.11641791044776119)}
************************************
tensor([[50257,   220, 50257, 21808,  3460,  7861,    27,    91,  5188,    47,
            91,    29, 25265,   540,  1605,  1466,  3095, 12735,  7914,  5112,
          1116,   641,  9528, 13763,   584,  1450,  5916, 25480,    82,   281,
          2422,  2779,   257,  4004,  7706,  3842, 13020,    27,    91,  5188,
            47,    91,    29]], device='cuda:0')
  Coming Attraction<|SEP|>fashionable American women midtown electronic equipment womens clothing hatred other men fishhooks an military base a favorite gang activity grain<|SEP|>The 1958 version of "The Marching Morons", a rioting police squad consisting mostly of policemen, military and plainclothesmen, takes over New York City streets in the aftermath of the financial crash of 1973

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.2609351432880845, recall=0.2392807745504841, fmeasure=0.24963924963924966), 'rougeL': Score(precision=0.1085972850678733, recall=0.0995850622406639, fmeasure=0.1038961038961039)}
************************************
tensor([[50257,   220, 50257,  5830,  6894,    27,    91,  5188,    47,    91,
            29,  2164,   549,  1213,  5163,  6163,   262,  1748, 14705, 14046,
           364, 41680,  5384,   884,  3434,   383, 25521,   267,   411,  2057,
         23751, 18556,  3653,  2661,  2922,  6049,    27,    91,  5188,    47,
            91,    29]], device='cuda:0')
  Deathworld<|SEP|>grubbers exchange selected the city planets dwellers besieged humans such attacks The radioactive ores food ore junkmen favor select severe<|SEP|>The story takes place in the distant future. Humanity has been devastated by war and chaos for millennia, and now the world is being regenerated. A new order of planetary governors has established a vast and technologically sophisti

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.5334476843910806, recall=0.4146666666666667, fmeasure=0.4666166541635409), 'rougeL': Score(precision=0.1646655231560892, recall=0.128, fmeasure=0.14403600900225058)}
************************************
tensor([[50257,   220, 50257,   383,   370, 11608, 38484,  1868,    27,    91,
          5188,    47,    91,    29, 37004, 10425,   664,    78,   359,   408,
         16790,  1402,  2042, 34896, 23441,  7183,  2769,  2272,  1528, 48851,
          6439,  3777,  1029,  1524,   257,  6737,  1657,    27,    91,  5188,
            47,    91,    29]], device='cuda:0')
  The Wailing Asteroid<|SEP|>radio signals recoilless pistol small black cubes cube readers deep space days interstellar unknown weapons high school a signal light<|SEP|>The novel concerns the adventures of the Wounded Soldier and the constabulary, during the Cold War between the Soviet Union and North America.


The story is told in flashbacks, as if the reader were reading the novel at the time.

I

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4654895666131621, recall=0.36295369211514394, fmeasure=0.4078762306610408), 'rougeL': Score(precision=0.17014446227929375, recall=0.13266583229036297, fmeasure=0.14908579465541494)}
************************************
tensor([[50257,   220, 50257,  1160,    11,   830,  1004,  6120,   739,   262,
          6896,    27,    91,  5188,    47,    91,    29,  6767,  3493,  7937,
         14101,  3048,  3819, 11000,  1204, 13435, 17219,   284,  9161, 36945,
           418, 14052,  1103,   220,  2846, 11561,  3200,   257, 11428,  5417,
          9234,    27,    91,  5188,    47,    91,    29]], device='cuda:0')
  20,000 Leagues under the Sea<|SEP|>Teacher ships devastating effects Other Marine life Advanced biology to investigate nemos motivation real  terms commander secret a mysterious sea monster<|SEP|>During a visit to the fictional submerged land of Atlantis, Dr. Pierre Aronnax, a French marine biologist and narrator of the story, receives a last-minute invit

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.5, recall=0.37617135207496655, fmeasure=0.4293353705118411), 'rougeL': Score(precision=0.17259786476868327, recall=0.12985274431057564, fmeasure=0.14820473644003057)}
************************************
tensor([[50257,   220, 50257, 10467, 11397,    27,    91,  5188,    47,    91,
            29,    70,   328,  5109,  6129,   373,   862, 10620, 25972,  3352,
         19435,   262,  2546,   286,   257, 17481, 27842,  4695, 25321,   262,
          1675,  3953, 33712,  9441,  5384,  1204,   257,   340,  6265, 40663,
            27,    91,  5188,    47,    91,    29]], device='cuda:0')
  Third Planet<|SEP|>gigantic fly wasps sizes chickens plans insects the size of a wolf ants animals descendants the To measure microbes survival humans life a it broke spaceship<|SEP|>The novel concerns a group of humans who build a spaceship and then try to scale it using insects.  Although the aliens succeed, the survivalist volunteers to host two large, independent animals o