In [1]:
import torch
from torch.utils.data import Dataset, DataLoader, random_split, RandomSampler, SequentialSampler

!pip install transformers
from transformers import GPT2LMHeadModel,  GPT2Tokenizer, GPT2Config, GPT2LMHeadModel
from transformers import AdamW, get_linear_schedule_with_warmup
import json

import pandas as pd  

     |████████████████████████████████| 4.0 MB 25.0 MB/s 
     |████████████████████████████████| 84 kB 3.5 MB/s 
     |████████████████████████████████| 880 kB 72.0 MB/s 
     |████████████████████████████████| 6.6 MB 63.0 MB/s 
     |████████████████████████████████| 596 kB 56.7 MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895260 sha256=3606969914e192710eaccc01fda3a3e31234b5d15e98e05109d40e9d86bdf8a1
  Stored in directory: /root/.cache/pip/wheels/87/39/dd/a83eeef36d0bf98e7a4d1933a4ad2d660295a40613079bafc9
Successfully built sacremoses
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
tokenizer = GPT2Tokenizer.from_pretrained('gpt2', bos_token='<|BOS|>', eos_token='<|EOS|>', pad_token='<|pad|>') #gpt2-medium


class GPT2Dataset(Dataset):
  def __init__(self, txt_list, tokenizer, gpt2_type="gpt2", max_length=768):
    self.tokenizer = tokenizer
    self.input_ids = []
    self.attn_masks = []
    for txt in txt_list:
      encodings_dict = tokenizer('<|BOS|>'+ txt + '<|EOS|>', truncation=True, max_length=max_length, padding="max_length")
      self.input_ids.append(torch.tensor(encodings_dict['input_ids']))
      self.attn_masks.append(torch.tensor(encodings_dict['attention_mask']))
    
  def __len__(self):
    return len(self.input_ids)

  def __getitem__(self, idx):
    return self.input_ids[idx], self.attn_masks[idx] 

Downloading:   0%|          | 0.00/0.99M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [6]:
# import pandas as pd
# xx = pd.read_csv('summary.csv', encoding = "ISO-8859-1")
# print(xx)

file = 'books_dataset.json'
with open(file) as train_file:
    dict_train = json.load(train_file)

# converting json dataset from dictionary to dataframe
train = pd.DataFrame.from_dict(dict_train, orient='index')
train.reset_index(level=0, inplace=True)

xx=train
# data = json.loads(books_dataset)
# df = pd.json_normalize(data['results'])
# xx = df
#print(xx.iloc[:,1])


In [7]:


summaries = xx.iloc[:,1].copy()

print(summaries)

0      <|BOS|>The Time Machine<|SEP|>time faints his ...
1      <|BOS|>The War of the Worlds<|SEP|>envious eye...
2      <|BOS|>A Princess of Mars<|SEP|>lower atmosphe...
3      <|BOS|>Youth<|SEP|>space aliens tiny dead iden...
4      <|BOS|>2 B R 0 2 B<|SEP|>population control ac...
                             ...                        
280    <|BOS|>Rip Foster Rides the Gray Planet<|SEP|>...
281    <|BOS|>Eastern Standard Tribe<|SEP|>members ps...
282    <|BOS|>Man of Many Minds<|SEP|>minds a secret ...
283    <|BOS|>The Players<|SEP|>aliens not nonsense t...
284    <|BOS|>Rip Foster in Ride the Gray Planet<|SEP...
Name: 0, Length: 285, dtype: object


In [8]:
dataset = GPT2Dataset(summaries, tokenizer, max_length=768)
train_size = int(0.7 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])


In [18]:
def preprocess_val_dataset(dataset):
  
  s = tokenizer.decode(dataset[0][0]).split('<|SEP|>')
  new_output = s[len(s)-1]
  new_output = s[len(s)-1]
  new_input = s[0]
  for i in range(1,len(s)-1):
    new_input = new_input+'<|SEP|>'+s[i]

  new_input = new_input + '<|SEP|>'
  #print(new_input)
  input_ids = tokenizer.encode(new_input, return_tensors='pt')
  output_ids = tokenizer.encode(new_output, return_tensors='pt')

  return input_ids[0], torch.ones(len(input_ids[0])), output_ids, new_output, new_input

In [19]:
batch_size=2
train_dataloader = DataLoader(
            train_dataset,  # The training samples.
            sampler = RandomSampler(train_dataset), # Select batches randomly
            batch_size = batch_size # Trains with this batch size.
        )
validation_dataloader = DataLoader(
            val_dataset, # The validation samples.
            sampler = SequentialSampler(val_dataset), # Pull out batches sequentially.
            batch_size = batch_size # Evaluate with this batch size.
        )

In [20]:
configuration = GPT2Config.from_pretrained('gpt2', output_hidden_states=False)

# instantiate the model
model = GPT2LMHeadModel.from_pretrained("gpt2", config=configuration)

# this step is necessary because I've added some tokens (bos_token, etc) to the embeddings
# otherwise the tokenizer and model tensors won't match up
model.resize_token_embeddings(len(tokenizer))


Embedding(50260, 768)

In [21]:
epochs = 5
learning_rate = 10e-4
warmup_steps = 1e2
epsilon = 1e-8

# this produces sample output every 100 steps
sample_every = 100

In [22]:
optimizer = AdamW(model.parameters(),
                  lr = learning_rate,
                  eps = epsilon
                )

total_steps = len(train_dataloader) * epochs

# Create the learning rate scheduler.
# This changes the learning rate as the training loop progresses
scheduler = get_linear_schedule_with_warmup(optimizer, 
                                            num_warmup_steps = warmup_steps, 
                                            num_training_steps = total_steps)

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,


In [23]:
import time
import datetime
import random
import tensorflow as tf

!pip install ipdb
device = torch.device("cuda")
model.cuda()
total_t0 = time.time()
model = model.to(device)

def format_time(elapsed):
    return str(datetime.timedelta(seconds=int(round((elapsed)))))
training_stats = []

for epoch_i in range(0, epochs):

    # ========================================
    #               Training
    # ========================================

    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
    print('Training...')

    t0 = time.time()

    total_train_loss = 0

    model.train()

    for step, batch in enumerate(train_dataloader):
        # cc = batch.copy()
        # labels = []
        # for en, ex in enumerate(cc[0]):
        #   import ipdb;ipdb.set_trace()
        #   ind_29 = (ex == 29).nonzero(as_tuple=True)
        #   ind_27 = (ex == 27).nonzero(as_tuple=True)
        #   batch[0][en] = cc[0][en][ind_29[0][1]+1:ind_27[0][2]]
        #   batch[1][en] = cc[1][en][ind_29[0][1]+1:ind_27[0][2]]
        #   labels.append(cc[0][en][ind_29[0][2]+1:])
        b_input_ids = batch[0].to(device)
        b_labels = batch[0].to(device)
        b_masks = batch[1].to(device)
        model.zero_grad()        

        outputs = model(  b_input_ids,
                          labels=b_labels, 
                          attention_mask = b_masks,
                          token_type_ids=None
                        )

        loss = outputs[0]  

        batch_loss = loss.item()
        total_train_loss += batch_loss

        # Get sample every x batches.
        if step % sample_every == 0 and not step == 0:

            elapsed = format_time(time.time() - t0)
            print('  Batch {:>5,}  of  {:>5,}. Loss: {:>5,}.   Elapsed: {:}.'.format(step, len(train_dataloader), batch_loss, elapsed))

            model.eval()

            sample_outputs = model.generate(
                                    bos_token_id=random.randint(1,30000),
                                    do_sample=True,   
                                    top_k=50, 
                                    max_length = 200,
                                    top_p=0.95, 
                                    num_return_sequences=1
                                )
            for i, sample_output in enumerate(sample_outputs):
                  print("{}: {}".format(i, tokenizer.decode(sample_output, skip_special_tokens=True)))
            
            model.train()

        loss.backward()

        optimizer.step()

        scheduler.step()

    # average loss over all of the batches.
    avg_train_loss = total_train_loss / len(train_dataloader)       
    
    training_time = format_time(time.time() - t0)

    print("")
    print("  Average training loss: {0:.2f}".format(avg_train_loss))
    print("  Training epoch took: {:}".format(training_time))
        
    # ========================================
    #               Validation
    # ========================================
    '''
    print("")
    print("Running Validation...")

    t0 = time.time()

    model.eval()

    total_eval_loss = 0
    nb_eval_steps = 0

    # Evaluate data for one epoch
    for batch in validation_dataloader:
        input_ids, masks, output_ids, output = preprocess_val_dataset(batch)
        #b_input_ids = batch[0].to(device)
        b_input_ids = input_ids.to(device)
        #b_labels = batch[0].to(device)
        b_labels = input_ids.to(device)
        #b_masks = batch[1].to(device)
        b_masks = masks.to(device)
        #print(f"DEBA: {b_labels}")
        #print(tokenizer.decode(b_input_ids))
        
        with torch.no_grad():        

            outputs  = model(b_input_ids, 
#                            token_type_ids=None, 
                             attention_mask = b_masks,
                            labels=b_labels)
          
            loss = outputs[0]  
            
        batch_loss = loss.item()
        total_eval_loss += batch_loss        
    '''
    total_eval_loss = total_train_loss
    avg_val_loss = total_eval_loss / len(validation_dataloader)

    validation_time = format_time(time.time() - t0)    

    print("  Validation Loss: {0:.2f}".format(avg_val_loss))
    print("  Validation took: {:}".format(validation_time))

    # Record all statistics from this epoch.
    training_stats.append(
        {
            'epoch': epoch_i + 1,
            'Training Loss': avg_train_loss,
            'Valid. Loss': avg_val_loss,
            'Training Time': training_time,
            'Validation Time': validation_time
        }
    )

print("")
print("Training complete!")
print("Total training took {:} (h:mm:ss)".format(format_time(time.time()-total_t0)))


======== Epoch 1 / 5 ========
Training...

  Average training loss: 7.12
  Training epoch took: 0:00:52
  Validation Loss: 16.56
  Validation took: 0:00:52

======== Epoch 2 / 5 ========
Training...

  Average training loss: 2.05
  Training epoch took: 0:00:56
  Validation Loss: 4.76
  Validation took: 0:00:56

======== Epoch 3 / 5 ========
Training...

  Average training loss: 1.56
  Training epoch took: 0:00:55
  Validation Loss: 3.62
  Validation took: 0:00:55

======== Epoch 4 / 5 ========
Training...

  Average training loss: 1.22
  Training epoch took: 0:00:56
  Validation Loss: 2.83
  Validation took: 0:00:56

======== Epoch 5 / 5 ========
Training...

  Average training loss: 1.00
  Training epoch took: 0:00:56
  Validation Loss: 2.32
  Validation took: 0:00:56

Training complete!
Total training took 0:04:35 (h:mm:ss)


In [24]:
model.eval()

prompt = "<|BOS|>we live in solar system<|SEP|> It has nine planets <|SEP|>"

generated = torch.tensor(tokenizer.encode(prompt)).unsqueeze(0)
generated = generated.to(device)

print(generated)

sample_outputs = model.generate(
                                generated, 
                                #bos_token_id=random.randint(1,30000),
                                do_sample=True,
                                no_repeat_ngram_size=2,  
                                top_k=5, 
                                max_length = 1000,
                                top_p=0.9, 
                                num_return_sequences=3
                                )
for i, sample_output in enumerate(sample_outputs):
  print("{}: {}\n\n".format(i, tokenizer.decode(sample_output, skip_special_tokens=True)))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[50257,   732,  2107,   287,  6591,  1080,    27,    91,  5188,    47,
            91,    29,   632,   468,  5193, 14705,  1279,    91,  5188,    47,
            91,    29]], device='cuda:0')
0: we live in solar system<|SEP|> It has nine planets <|SEP|>The story begins with the discovery of a planet, Helium, which is located in the Helian system. Heliators around the world discover that Helia is home to a civilisation of "gigantic green-skinned, blue-robed, red-necks", and that its inhabitants are intelligent and technologically advanced. The story ends with Helios, a newly discovered planet.


 n n n terrestre stars ter star your served dishes meal And adults hell Sun, sun planets Planet Year The Year stars Sun Planet Year Sun Planet name Planet Born Planet year

 George Washington George "Wellington" West, Jr.
 Seven planets in Heliconia

, named "Little Hel" by the locals
The sun is a starless world with a sunlike "darkened" atmosphere. Its interior is made of thick, frozen 

In [ ]:
!pip install rouge/requirements.txt
!pip install rouge-score
from rouge_score import rouge_scorer


for batch in validation_dataloader:
    input_ids, masks, output_ids, ref_story, prompt = preprocess_val_dataset(batch)
    #b_input_ids = batch[0].to(device)
    b_input_ids = input_ids.to(device)
    #b_labels = batch[0].to(device)
    b_labels = input_ids.to(device)
    #b_masks = batch[1].to(device)
    b_masks = masks.to(device)
    #print(f"DEBA: {b_labels}")
    #print(tokenizer.decode(b_input_ids))
  
    #prompt = input_ids

    generated = torch.tensor(tokenizer.encode(prompt)).unsqueeze(0)
    generated = generated.to(device)

    print(generated)

    sample_outputs = model.generate(
                                    generated, 
                                    #bos_token_id=random.randint(1,30000),
                                    do_sample=True,
                                    no_repeat_ngram_size=2,  
                                    top_k=5, 
                                    max_length = 1000,
                                    top_p=0.9, 
                                    num_return_sequences=3
                                    )
    
    for i, sample_output in enumerate(sample_outputs):
      s =  tokenizer.decode(sample_output, skip_special_tokens=True)
      print(s)
      scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
      scores = scorer.score(s, ref_story)
      print(scores)
      print("************************************")

          
      

ERROR: Invalid requirement: 'rouge/requirements.txt'
Hint: It looks like a path. File 'rouge/requirements.txt' does not exist.


Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[50257,   220, 50257,  1810, 10572,   286,  8706,    27,    91,  5188,
            47,    91,    29, 36022,  1879,  1010, 12525,  3656, 21303,  2093,
         27487,  1318,  8499,  1545,   262,   911, 27725,  2581, 39439,  3338,
          4398,  8791,   922,  6266,  5093, 13559,  1451,    27,    91,  5188,
            47,    91,    29]], device='cuda:0')
  Warlord of Mars<|SEP|>yellow Carters ally wife unmask disguise Thereafter friend the Shangs request fleets safe haven encounter good orders north polar cap<|SEP|>The novel concerns a war between the Green Men and the "Bad Bloods" (actually the White Walkers) who occupied the planet Issus in the decades-long conflict that occupied their world.
The plot builds tension between Issuance (Green) and his counterpart Valeria, a ruthless and ruthless client-apprentice of the Khylem (a clan of green men). Issuing a peace treaty with Issues, Issures the mercantile Issgard, who has trained him to be a tactician, and persuades him that h

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.46455223880597013, recall=0.3221216041397154, fmeasure=0.3804430863254393), 'rougeL': Score(precision=0.17164179104477612, recall=0.11901681759379043, fmeasure=0.1405653170359053)}
************************************
  Warlord of Mars<|SEP|>yellow Carters ally wife unmask disguise Thereafter friend the Shangs request fleets safe haven encounter good orders north polar cap<|SEP|>During the year 1866, ships of several nations spot a band of renegade Picts, who have crossed into the unknown south Pacific Ocean. The fleet is attacked and the Pict fleet takes a stand. Captain Nemo is the first to warn the allies.
The Shang brothers, led by seafaring merchant ships, are preparing to attack the fleet and steal supplies from the merchant. Nemos motivation is implied to be both a desire for revenge upon the previous hijacking of the Golden Hornet, and a hatred for the new Americans. While visiting the Barbicane Islands, Nemotsuhito, the son of a merchantman and mas

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.5178875638841567, recall=0.39790575916230364, fmeasure=0.4500370096225018), 'rougeL': Score(precision=0.1788756388415673, recall=0.13743455497382198, fmeasure=0.15544041450777202)}
************************************
tensor([[50257,   220, 50257,   383, 19357, 16734,    27,    91,  5188,    47,
            91,    29, 41915,  5006, 11863, 32199, 28475,  9265,  5830, 24569,
          3815,  1204, 12252,  1295,  8166,   262, 43386,   257,  2440,  2861,
           995, 49112,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  The Poison Belt<|SEP|>escape cars oxygen poisonous ether humanity Death Victorian values life fires place destruction the cylinders a higher worth world challengers<|SEP|>Euthan Tycho, a young American chemist, escapes his abusive wife and sets off on an expedition to rescue a group of Victorians. He is set upon by the forces that occupied his country.
The story is narrated by Tyco, who claims he is a hero of sorts, and

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.27136431784107945, recall=0.23910171730515192, fmeasure=0.25421348314606745), 'rougeL': Score(precision=0.10644677661169415, recall=0.09379128137384413, fmeasure=0.0997191011235955)}
************************************
tensor([[50257,   220, 50257,   383,  2159,   351,   257, 39255, 48432,    27,
            91,  5188,    47,    91,    29,   563,  5907,  6156,  4472,  3551,
           262,  5440, 12536,   257,  1029,  2324,  2272,  2779,    11,   366,
          1477,  4980,   617,  1295,  1178,   812,   257, 15758,  2003,    27,
            91,  5188,    47,    91,    29]], device='cuda:0')
  The World with a Thousand Moons<|SEP|>ryns ancient enemy write the planet bases a high security space base, "shading some place few years a imagined future<|SEP|>The story begins in 2100, when the world of Greys is attacked by a hostile client state that plans to take over the entire Solar System. Grey is claimed by the Terran Navy and its allies as a client planet, a

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.10384068278805121, recall=0.09851551956815115, fmeasure=0.10110803324099724), 'rougeL': Score(precision=0.05689900426742532, recall=0.05398110661268556, fmeasure=0.0554016620498615)}
************************************
tensor([[50257,   220, 50257,   383,   370, 11608, 38484,  1868,    27,    91,
          5188,    47,    91,    29, 37004, 10425,   664,    78,   359,   408,
         16790,  1402,  2042, 34896, 23441,  7183,  2769,  2272,  1528, 48851,
          6439,  3777,  1029,  1524,   257,  6737,  1657,    27,    91,  5188,
            47,    91,    29]], device='cuda:0')
  The Wailing Asteroid<|SEP|>radio signals recoilless pistol small black cubes cube readers deep space days interstellar unknown weapons high school a signal light<|SEP|>The Wailers escape from a crashed spaceship and begin their interstellar flight to find and destroy the alien Baldies. They encounter a group of humans who want them dead, but are too scared to open fire.
The group d

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4590690208667737, recall=0.38858695652173914, fmeasure=0.42089771891096395), 'rougeL': Score(precision=0.17014446227929375, recall=0.14402173913043478, fmeasure=0.15599705665930833)}
************************************
tensor([[50257,   220, 50257,   383,  3862, 10850,    27,    91,  5188,    47,
            91,    29, 23563,   277,  6003,   465,  4572,   262,  2562,  3476,
           831,   577, 28459,  2972,  1528,   284,  8588,   257,  6915, 11055,
          6180,  9441,  3236, 44571,  4334,  8215,    27,    91,  5188,    47,
            91,    29]], device='cuda:0')
  The Time Machine<|SEP|>weather faints his machine the easy lichenose vegetation various days to possess a desk template evening survival huge butterflies heavy doors<|SEP|>The Time machine is powered by a subterranean energy source called the "Earth Current". It is programmed to conserve power when weather conditions change and to periodically recharge the accumulators. When the Earth Cur

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.48825503355704697, recall=0.3784135240572172, fmeasure=0.42637362637362636), 'rougeL': Score(precision=0.174496644295302, recall=0.1352405721716515, fmeasure=0.1523809523809524)}
************************************
tensor([[50257,   220, 50257,   383,  1810,   286,   262, 19946,    27,    91,
          5188,    47,    91,    29,    73, 15746,  2951,  9017,   674,   465,
          3352,  2272,  3687,  1956,   674,   262,  1839, 12108,  1320,   883,
           356,    27,    91,  5188,    47,    91,    29]], device='cuda:0')
  The War of the Worlds<|SEP|>jealous eyes minds our his plans space East land our the won Gulf That those we<|SEP|>The story opens in the jungles of South America. A tribe of nomads sets up camp on the Amazon, in search of gold and a road to riches. The gold is discovered and taken by a tribe led by an Englishman named "Little John." Little John, who happens to be a member of a rival tribe called the Picts, buys the gold worth several t

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.04016620498614958, recall=0.03866666666666667, fmeasure=0.03940217391304348), 'rougeL': Score(precision=0.027700831024930747, recall=0.02666666666666667, fmeasure=0.02717391304347826)}
************************************
tensor([[50257,   220, 50257,   383, 12136, 12635,    27,    91,  5188,    47,
            91,    29,  2536,   858,  6147, 43828, 11597,  1918, 24823,   584,
          3211, 12604,  8166, 41197, 15268, 36834, 34896,   257,  1748, 28408,
           430,   704, 12212, 15095,   274,   290, 15716, 13099,    11,  3956,
            27,    91,  5188,    47,    91,    29]], device='cuda:0')
  The Metal Monster<|SEP|>strange metal animate Things death rays other armaments destruction colossal shapes sentient cubes a city tetrahedrons globes and Ventnor, brother<|SEP|>The story is told in the present day through the use of a mind-altering device called the "silk" which can be turned off and on.
Professor Pierre Aronnax, a French éminence grise, who 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.20606060606060606, recall=0.16707616707616707, fmeasure=0.18453188602442333), 'rougeL': Score(precision=0.09090909090909091, recall=0.07371007371007371, fmeasure=0.0814111261872456)}
************************************
tensor([[50257,   220, 50257, 37448,   338, 29221,   286,  8706,    27,    91,
          5188,    47,    91,    29,    65, 44965,  8526,  5186,  1128, 15204,
         49408, 13758, 32508,  5112, 20178,  2272, 14803,  7937,  1049, 14395,
          1717,  9886, 26842,  2485,   262, 16997,  1692, 13384,    27,    91,
          5188,    47,    91,    29]], device='cuda:0')
  Edison's Conquest of Mars<|SEP|>bacterial illness electric repulsion derelict Martian equipment giants space suits ships great celebration Edisons ray gun the surviving human slaves<|SEP|>The novel, which concerns the revolt of Martian society after the shortsightedness of Edison and his colleagues during the suppression of the rebellion of Julius Janis Dax, describes the ad

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.3177570093457944, recall=0.2579013906447535, fmeasure=0.2847173761339847), 'rougeL': Score(precision=0.13395638629283488, recall=0.10872313527180784, fmeasure=0.12002791346824841)}
************************************
tensor([[50257,   220, 50257,   383,  3370,  1424,   286,   317,   457,   273,
            27,    91,  5188,    47,    91,    29,  8929, 11881,   262,  3223,
         39456,  2196, 14355,   257,  1862, 11503,   408,  8848, 22215, 11428,
          1956,  1281,    12, 47116,  2003,   607,  1310,  6621, 43272,    27,
            91,  5188,    47,    91,    29]], device='cuda:0')
  The Jewels of Aptor<|SEP|>high radiation the dark mutants version civilization a young priestess boat goddess mysterious land post-atomic future her little sister sailor<|SEP|>The novel concerns the adventures of a high-security space ship survivor, Dr. Elihu Whipple, voyaging solo in space. While on the ship, he discovers that he is the last survivor of an important an

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.0944206008583691, recall=0.0859375, fmeasure=0.08997955010224949), 'rougeL': Score(precision=0.05150214592274678, recall=0.046875, fmeasure=0.049079754601226995)}
************************************
tensor([[50257,   220, 50257,  1869,   286,  4650, 10175,    82,    27,    91,
          5188,    47,    91,    29, 10155,    82,   257,  3200,  2139,  5797,
           262,  2694, 17545,   383,  5337,   508,    27,    91,  5188,    47,
            91,    29]], device='cuda:0')
  Man of Many Minds<|SEP|>minds a secret service agent the ability adventures The novel who<|SEP|>The novel concerns the adventures of George Hanlon, a veteran of the Cold War who goes on the run from the Service after being exposed as a Soviet agent (soldier) in the American Civil War.
The protagonist is Hanlan Tuning, an agent with the Free Men's Union (Famously Accompanying the Union), a newly established and independent nation that has been striving to establish itself as an independ

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.023224043715846996, recall=0.02096177558569667, fmeasure=0.0220349967595593), 'rougeL': Score(precision=0.017759562841530054, recall=0.016029593094944512, fmeasure=0.016850291639662993)}
************************************
tensor([[50257,   220, 50257,   383,  4380,   286,   262,  2619, 16291,    27,
            91,  5188,    47,    91,    29,   301,   403,  1494,  3817,  5718,
           364,   416, 31634,  2180, 37071,   314,  2865,   952,  6300, 40255,
          6937,   679, 18240,   284,  1842,  3687,  2106, 34254, 26884,   126,
           123, 23141, 35906,  5358, 10802,   422,  7858, 15776,  1393,    27,
            91,  5188,    47,    91,    29]], device='cuda:0')
  The People of the Black Circle<|SEP|>stun kill mountaineers by Conan previous mythical Iborio versions equivalents constant He stole to love East history Bj�rn conflict confusion from turanium interest<|SEP|>The story takes place in the year 1570, in Iceland. A band of stoners, called

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.47509578544061304, recall=0.3333333333333333, fmeasure=0.39178515007898895), 'rougeL': Score(precision=0.1896551724137931, recall=0.13306451612903225, fmeasure=0.15639810426540282)}
************************************
tensor([[50257,   220, 50257,  1770,    13, 48086,  1056,    27,    91,  5188,
            47,    91,    29,  6042,   262, 15268, 34579,  2272, 21600,  9029,
          5748,  1175,  1336,  2198,  9265,   257,  8756,  3530, 41454,  6156,
          4701,   262,   406, 42004,  1912,  7937,    27,    91,  5188,    47,
            91,    29]], device='cuda:0')
  Mr. Spaceship<|SEP|>life the shapes External space mechanic spaceships war full check humanity a alien Street Kramer ancient teacher the Lifestyle based ships<|SEP|>The story opens in a world where people have lived for billions of years, but have died out or are buried in Earth's crust. Professor Kramer, an engineer working with the Soviet Union in the buildup to World War I, has just beg

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.24167872648335745, recall=0.20927318295739347, fmeasure=0.22431161853593012), 'rougeL': Score(precision=0.0955137481910275, recall=0.08270676691729323, fmeasure=0.08865010073875083)}
************************************
tensor([[50257,   220, 50257,   383, 40981,  5451,    27,    91,  5188,    47,
            91,    29, 40093,  1525,  3367,   284, 19818,  6300,  5995,  1709,
           654,  1966,  4572, 36945,   418, 11816,  1295,  5417,  1241,  8244,
           366,    43, 11690,  6541,  2046,   627,   259,   500, 45558,   378,
          2972,  1528,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  The Mysterious Island<|SEP|>nearby son to retrieve versions Home Brings former machine nemos hiding place sea level squad "Lincoln guns fire quinine sulphate various days<|SEP|>The story begins at the turn of the 17th century, in Pennsylvania. The 17-year-old protagonist, John Fairlie, is on the loose after his purchase of a farmhouse in ru

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.475, recall=0.3280212483399734, fmeasure=0.38805970149253727), 'rougeL': Score(precision=0.18269230769230768, recall=0.12616201859229748, fmeasure=0.14925373134328357)}
************************************
tensor([[50257,   220, 50257, 12197, 35337,   262,   370,   549,    27,    91,
          5188,    47,    91,    29, 19425,  4695, 12928,  7918,  2770,  5538,
          4547,   281,  9812, 12967,    12,  2339,  7185, 29404,   262,  8564,
           266,   549,  2961,  5273,   257,   845, 12661, 19207,    27,    91,
          5188,    47,    91,    29]], device='cuda:0')
  Beyond Lies the Wub<|SEP|>food animals departure mythological figures understanding an enormous pig-like creature bursts the sensitive wub earlier conversation a very intelligent confrontation<|SEP|>During an important adventure the protagonists are stranded on a primitive planet, having been captured by a group of large animals. The main protagonist, Dr. Henry Louis XVI, is puzzled by th

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.15306122448979592, recall=0.13092269326683292, fmeasure=0.14112903225806453), 'rougeL': Score(precision=0.06851311953352769, recall=0.05860349127182045, fmeasure=0.06317204301075269)}
************************************
tensor([[50257,   220, 50257,   317,  8449,   286,  8706,    27,    91,  5188,
            47,    91,    29,  1084,   273, 20938, 30980,  4077,    12, 41412,
          3265,   262, 34870,  2266, 32508,  3234, 47262, 33546,  1049,  2700,
           257,  3200,  5735, 38829,  2438, 28526,  2861,    27,    91,  5188,
            47,    91,    29]], device='cuda:0')
  A Princess of Mars<|SEP|>minor atmospheric Pressure green-skinned population the humanoid red Martian race superhuman agility great force a secret telepathic code Martial worth<|SEP|>A Martian woman, beautiful and strong, has a remarkable gift for psionics. A Martian settler, Lady Luck, who had been enslaved by the Red Brotherhood, escapes to the surface world of Terra and is marr

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.2859399684044234, recall=0.24197860962566844, fmeasure=0.2621288921071687), 'rougeL': Score(precision=0.12954186413902052, recall=0.10962566844919786, fmeasure=0.11875452570601014)}
************************************
tensor([[50257,   220, 50257, 18037,   287, 44418,  2852,    64,    27,    91,
          5188,    47,    91,    29,  9150,  6463,   571,   874,  6180,   416,
         31634, 25304,  2565,  1310,  4676,   257,  2619,  7491,    69,  3699,
         39904,   262, 42939, 18692,  3334, 11503,  1029,  7165,  1450,    27,
            91,  5188,    47,    91,    29]], device='cuda:0')
  Shadows in Zamboula<|SEP|>position cannibals evening by Conan ironic sense little camera a Black Darfarian cannibal the Hungry Desert High priest high crazy men<|SEP|>The story begins in a small Zambala village, Zambanga, where the hungry cannabals live. The village is sleepy and dusty, but after the arrival of the local priest and the semi-comic reliefist Medic, Conan

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.37540453074433655, recall=0.3328550932568149, fmeasure=0.35285171102661594), 'rougeL': Score(precision=0.15210355987055016, recall=0.13486370157819225, fmeasure=0.1429657794676806)}
************************************
tensor([[50257,   220, 50257,   383, 19357, 16734,    27,    91,  5188,    47,
            91,    29,  5143,  8272,  8217, 11863, 32199, 28475,  9265,  1918,
         24569,  3815,  1204, 12252,  1295,  8166,   262, 43386,   257,  2440,
          1988,   995, 10772,  9302,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  The Poison Belt<|SEP|>runaway machines oxygen poisonous ether humanity death Victorian values life fires place destruction the cylinders a higher value world Challengers<|SEP|>The story is set in a world where humans have been enslaved by a "dark side" called the "Consolidation", a cult dedicated to a god-like being called "Savior", called Jup (prince) Mors. The book tells of a vision of an "Object Compas

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.26766917293233083, recall=0.24151967435549526, fmeasure=0.253922967189729), 'rougeL': Score(precision=0.10225563909774436, recall=0.09226594301221167, fmeasure=0.09700427960057062)}
************************************
tensor([[50257,   220, 50257,   383,  9164,  2159,    27,    91,  5188,    47,
            91,    29, 28116,   282,   584,  5384,   812,  3942, 17555,  5564,
           742,   684,  1218,  5296,   262,  2187, 38008, 29979,  2318,   684,
         43835,    12,  3653, 17851,  1096, 34066,  1175,   257,  1862,    27,
            91,  5188,    47,    91,    29]], device='cuda:0')
  The Lost World<|SEP|>several other humans years Indian guides Roxtons second trip the whole plateau robber barons ape-men categorize fossils war a young<|SEP|>A young man from another world, a Neanderthal, attempts to help a group of ape men regain their human form by retrieving a skull of a man they had saved from a cave. The expedition departs for the plateau, where 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4966216216216216, recall=0.4123422159887798, fmeasure=0.4505747126436781), 'rougeL': Score(precision=0.17567567567567569, recall=0.1458625525946704, fmeasure=0.15938697318007664)}
************************************
tensor([[50257,   220, 50257, 21808,  3460,  7861,    27,    91,  5188,    47,
            91,    29,    37,  5880,  1605,  1466,  8329,  3641,  7914,  8244,
          6926,   338,  9528,  5465,  3819,  1869, 26569,   257,  2422,  2779,
           257,  4004,  4097,  5517, 13020,    27,    91,  5188,    47,    91,
            29]], device='cuda:0')
  Coming Attraction<|SEP|>Fashion American women Town center electronic squad Women's clothing hate Other Man hooks a military base a favorite band exercise grain<|SEP|>In the aftermath of a World War I victory celebration, soldiers from the Free World take part in an effort to organize an army to counter the growing threat of Communism. They also wear uniforms similar to that of the First World Trad

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.24060150375939848, recall=0.2206896551724138, fmeasure=0.23021582733812948), 'rougeL': Score(precision=0.10075187969924812, recall=0.09241379310344827, fmeasure=0.09640287769784173)}
************************************
tensor([[50257,   220, 50257,   383, 23998,    27,    91,  5188,    47,    91,
            29, 43131,  5519,  3777,  2469,   321,  1436,  6953,  2272,   262,
          2104,  7840,  2063,  1175,   257, 19999,  5440,   383,  7186, 11278,
          2276,  5163, 36399,   272,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  The Answer<|SEP|>nuclear scientists weapons negamatter iron space the entire northern half war a meteor planet The resulting explosion general exchange Argentinean<|SEP|>The novel concerns the fallout from the first war between the Terran and Martians, between their nations. The novel begins with the discovery of a radioactivity in a desolate, desolate world, called “Machiavelli's Hill’, in May 1863. A g

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.1340057636887608, recall=0.12077922077922078, fmeasure=0.12704918032786885), 'rougeL': Score(precision=0.06484149855907781, recall=0.05844155844155844, fmeasure=0.06147540983606558)}
************************************
tensor([[50257,   220, 50257,   383,  3943,   286,   262, 32547, 11397,    27,
            91,  5188,    47,    91,    29,   847, 14705, 29973,  7032,  5788,
           734, 13526,  7923,  7937,   257,  1345,   315, 27625,  4074,   262,
          8756, 13584,  4547, 12465,  8320,   602,  1402, 17226,  5194,    27,
            91,  5188,    47,    91,    29]], device='cuda:0')
  The Secret of the Ninth Planet<|SEP|>other planets gravitational fields stars two dumbbell ships a Plutonian ship the alien mutual understanding tremendous accelerations small atomic bomb<|SEP|>During the year 1866, the United States government avidly pursues discoveries in the fields of space and time, and in pursuit of their discovery the discovery of two new planet

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.46688741721854304, recall=0.39385474860335196, fmeasure=0.42727272727272725), 'rougeL': Score(precision=0.18211920529801323, recall=0.15363128491620112, fmeasure=0.16666666666666669)}
************************************
tensor([[50257,   220, 50257,   383, 26983,    27,    91,  5188,    47,    91,
            29, 20337,  2846,  5384, 13767,   649,   530, 18944,  3665,  1956,
           257,  1605,  1175, 42351,  5358, 13275, 24804, 36892,  2628, 13644,
           257,  4523,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  The Defenders<|SEP|>area terms humans sophisticated new one Weapons powerful land a American war planner conflict tunnel gigantic bunker groups survivors a nuclear<|SEP|>The novel concerns a war between the Terran Navy and a small group of humans, intended to wipe out large numbers of enemy ships and bases, and develop a concept for a "bomb-thrower". The novel is set in a future where humans have developed sophistica

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.3413897280966767, recall=0.2931258106355383, fmeasure=0.3154221912072575), 'rougeL': Score(precision=0.13293051359516617, recall=0.11413748378728923, fmeasure=0.12281926029309143)}
************************************
tensor([[50257,   220, 50257,   383,  3862, 10850,    27,    91,  5188,    47,
            91,    29,  2435,   277,  6003,   465,  4572,   262,  2829,  3476,
           831,   516, 28459,  1811,  1528,   898,   257, 45052,  2746,  1755,
          9441,  9812, 44571,  4334,  8215,    27,    91,  5188,    47,    91,
            29]], device='cuda:0')
  The Time Machine<|SEP|>time faints his machine the simple lichenous vegetation several days own a tabletop model night survival enormous butterflies heavy doors<|SEP|>The story is set in the distant future, in which time has seemingly turned into a literal twilight. The main protagonist, Simon Dunark, sets off for a life in peace, investigating a case that has been going on for several millennia. 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.49246231155778897, recall=0.3793548387096774, fmeasure=0.4285714285714286), 'rougeL': Score(precision=0.17587939698492464, recall=0.13548387096774195, fmeasure=0.15306122448979595)}
************************************
tensor([[50257,   220, 50257,   383, 19821,  9561,  4687,    27,    91,  5188,
            47,    91,    29,  1169, 11198, 13570, 24242,   938,  6843, 13521,
          1302,    12, 17749,  2420, 40752,   257,  2910, 21419,   281,  4430,
          5797,   326,   995,  5093,   383,    27,    91,  5188,    47,    91,
            29]], device='cuda:0')
  The Door Through Space<|SEP|>the Double printing differs last chapter 1979 stand-alone text Towns a blood feud an intelligence agent that world north The<|SEP|>The story begins in May 1979 in a small town in the South Pacific Ocean. A year later, an accident results in explosions and an explosion in an abandoned ship. The ship is transporting a team of scientists to a remote island off the coast 

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.05532503457814661, recall=0.05121638924455826, fmeasure=0.05319148936170213), 'rougeL': Score(precision=0.0318118948824343, recall=0.029449423815621, fmeasure=0.030585106382978722)}
************************************
tensor([[50257,   220, 50257,  3334,  1322,   287,   367,  2530,    27,    91,
          5188,    47,    91,    29, 10823,  1502,  3338,  7777,  5735,  6978,
            82,   661,  1807,  2208,  1450,  4043,   644,   338,   428,  3294,
         21528,   262, 14112,  2888, 42859,  2536,  9101,    76,  1675,    68,
           257,  7104, 12763,  6118,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  Highways in Hiding<|SEP|>rock order safe houses telepaths people thought super men wait what's this multiple plots the infected member Mekström Toe a hidden highway Program<|SEP|>The story takes place in a world of telepathic communication and Internet-wide communication. The main protagonist, Dr. Hoddy Ringo, who happens to be

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.15429403202328967, recall=0.13984168865435356, fmeasure=0.1467128027681661), 'rougeL': Score(precision=0.07132459970887918, recall=0.06464379947229551, fmeasure=0.06782006920415223)}
************************************
tensor([[50257,   220, 50257, 12197,   262, 19821,    27,    91,  5188,    47,
            91,    29,  3849, 33571,   257,   269,  1347,  2238, 21328, 15347,
           546,  1885,  6368,   383,   262,  6565,    11,  9480,  5995, 33424,
          2728,   465,  7393,  2589,  5118,  4151,   673,  2802,  3656,    27,
            91,  5188,    47,    91,    29]], device='cuda:0')
  Beyond the Door<|SEP|>interviews a cuckoo Clock passionate about antiques The the empty, calm Home Autumn cause his neck moment chair eye she mother wife<|SEP|>The novel opens with the story of an elderly gentleman, mourning his passing. As he ponders his fate, he is moved by a passer-by to sit next to his bed, where he sees a television set. The man is lying on the b

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.14076246334310852, recall=0.12885906040268458, fmeasure=0.1345480028030834), 'rougeL': Score(precision=0.07038123167155426, recall=0.06442953020134229, fmeasure=0.0672740014015417)}
************************************
tensor([[50257,   220, 50257,   317, 32508, 28032,    27,    91,  5188,    47,
            91,    29, 31629, 12972, 43591,  5448, 10712,  2801,   383, 14207,
          1097,  7185,  8109,   477,   262,   257,   890,  2092,   284,   257,
          6512,  1125, 21768,  3352,   351, 41192,  8977,  2686,    27,    91,
          5188,    47,    91,    29]], device='cuda:0')
  A Martian Odyssey<|SEP|>little pyramids healthy tissue ill The Following car creature creatures all the a long similar to a bird chewy plans with tentacles dust shoot<|SEP|>The story takes place in the year 1866 in New Mexico. Professor Abednego, a British settler who happens to be visiting the area, is moved to the remote town of Kapuskasing to procure a chest made of a simi

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4599659284497445, recall=0.3562005277044855, fmeasure=0.40148698884758366), 'rougeL': Score(precision=0.17546848381601363, recall=0.1358839050131926, fmeasure=0.15315985130111526)}
************************************
tensor([[50257,   220, 50257,   383, 49790, 33406,    27,    91,  5188,    47,
            91,    29,    85,   419,  1063,   517,   867,  4553,  2116,    12,
            82,   436,  1397,   383,  2656,   262,  9155,   317, 28488,   278,
         42726, 26329,  5976,   863, 14705,   649,  1204,  5107, 20732,   257,
           640,    27,    91,  5188,    47,    91,    29]], device='cuda:0')
  The Vortex Blaster<|SEP|>vortices more many separate self-sustaining The original the loose A churning vortex uninhabited planets new life forms explosives a time<|SEP|>A vortex blaster pistol fires a projectile propelled by a small explosive that travels at faster speed than light and slows down when fired. It slows the projectile by 100-foot spheres of l

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4644628099173554, recall=0.3668407310704961, fmeasure=0.4099197665937272), 'rougeL': Score(precision=0.17355371900826447, recall=0.1370757180156658, fmeasure=0.15317286652078774)}
************************************
tensor([[50257,   220, 50257,   383,  4403, 18383,  3205,   575,  8623,    27,
            91,  5188,    47,    91,    29,  6042, 27602,   292,   505,   532,
          7356,  2661,  8684,   400,  3996,  6317,   257, 15556,   481,  3770,
         31845,  3115,   777,  2877, 14752,   262,  5290, 11029,    27,    91,
          5188,    47,    91,    29]], device='cuda:0')
  The Big Trip Up Yonder<|SEP|>life gerasone - jail favor 76th bed reaction a revised will prison grandson Super these living arrangements the worst sleeping<|SEP|>The story begins in prison, where a group of young prisoners are gathered to prepare for the arrival of their grandfather. They spend the afternoon sleeping in a cellblock, investigating the possibility of a biological

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.2996845425867508, recall=0.25745257452574527, fmeasure=0.27696793002915454), 'rougeL': Score(precision=0.10252365930599369, recall=0.08807588075880758, fmeasure=0.09475218658892127)}
************************************
tensor([[50257,   220, 50257,   383, 23998,    27,    91,  5188,    47,    91,
            29, 43131,  5519, 18944,  2469,   321,  1436,  6953,  2272,   262,
          2472,   422,   262,  5093,  1724,    11,  7090,  1175,   257, 19999,
           578,  5440,   383,  7186, 11173,  2276,  5163, 36399,    27,    91,
          5188,    47,    91,    29]], device='cuda:0')
  The Answer<|SEP|>nuclear scientists Weapons negamatter iron space the total from the north means, medium war a meteorite planet The resulting burst general exchange Argentine<|SEP|>The story opens in the present day as the nuclear scientists recover uranium from a crashed spaceship. They begin building a large shelter for the survivors of a winter storm. The ship's crew memb

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.14782608695652175, recall=0.12927756653992395, fmeasure=0.13793103448275862), 'rougeL': Score(precision=0.07246376811594203, recall=0.06337135614702155, fmeasure=0.06761325219743071)}
************************************
tensor([[50257,   220, 50257,  2907,   805,   338,  6785,    27,    91,  5188,
            47,    91,    29,  1044,   812,  3436,  5654,  1943,  2745, 20281,
         34857, 18440,   262,  8718, 19472, 10675,   257,  2272,  8848, 29640,
         36246, 10472,  8780,  1321,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  Starman's Quest<|SEP|>land years alone scientific success weeks protagonist Maintenance revision the hyperdrive centuries a space boat Twins contraction Download crucial information<|SEP|>The novel concerns the maintenance of a ship's hyper-drive, and the problems associated with this work.

The story begins in May 1863, aboard the Victory of Saratoga. A ship is accidentally set to rest on a methane gas

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.24537037037037038, recall=0.2081151832460733, fmeasure=0.22521246458923513), 'rougeL': Score(precision=0.08950617283950617, recall=0.07591623036649214, fmeasure=0.08215297450424928)}
************************************
tensor([[50257,   220, 50257, 21808,  3460,  7861,    27,    91,  5188,    47,
            91,    29, 25265,   540,  1605,  1466,  3095, 12735,  7914,  5112,
          1116,   641,  9528, 13763,   584,  1450,  5916, 25480,    82,   281,
          2422,  2779,   257,  4004,  7706,  3842, 13020,    27,    91,  5188,
            47,    91,    29]], device='cuda:0')
  Coming Attraction<|SEP|>fashionable American women midtown electronic equipment womens clothing hatred other men fishhooks an military base a favorite gang activity grain<|SEP|>The novel concerns the adventures of the mid-1960s and '70s, with its narrator, Dick Fairlie, a thirtysomething punk who has gone on the road in a pants suit and comes out dressed in pants. He soon discovers

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.26998491704374056, recall=0.23246753246753246, fmeasure=0.24982554082344735), 'rougeL': Score(precision=0.10105580693815988, recall=0.08701298701298701, fmeasure=0.09351011863224007)}
************************************
tensor([[50257,   220, 50257,  8865,  3827, 34787,    27,    91,  5188,    47,
            91,    29, 42276,   262,  1310, 35609,  2779, 11772,   257,  6129,
         11898, 14039,  6156,  9846,  5954,   866, 13936,  6611,    11,  6611,
          9192, 12840,   588,   257, 10441, 34870,   416,   911,  1236,    27,
            91,  5188,    47,    91,    29]], device='cuda:0')
  Storm Over Warlock<|SEP|>crew the little terrestrial base shelter a fly disk Contact ancient memories pulled down exploration blow, blow fool trap like a dragon humanoid by Shann<|SEP|>The story begins in May 1863 in Hamburg, Germany. Professor Abner Grego, an Englishman living in the country, and his nephew Axel Axel find themselves stranded on an abandoned island o

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.4388111888111888, recall=0.32512953367875647, fmeasure=0.37351190476190477), 'rougeL': Score(precision=0.16433566433566432, recall=0.12176165803108809, fmeasure=0.13988095238095238)}
************************************
tensor([[50257,   220, 50257, 29496, 18489,   287, 21640,   262, 12723, 11397,
            27,    91,  5188,    47,    91,    29,    69,  1480,   540,  2587,
           987,    12, 15271, 26390,  5899, 41899,  1505,   779,   262, 27460,
         10999, 40343,   281,  1630,   257, 11000,     8, 19090,    13,  5855,
            49,   541,  4943,  6554,  2272,    12,  5146,  7548,    27,    91,
          5188,    47,    91,    29]], device='cuda:0')
  Rip Foster in Ride the Gray Planet<|SEP|>fissionable material inter-service rivalry pure thorium use the asteroid belt Governments an control a Marine) Lt. ("Rip") agents space-going equivalent<|SEP|>The action takes place in an intergalactic minor world where the majority of the crew are human-li

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.09170305676855896, recall=0.08502024291497975, fmeasure=0.08823529411764705), 'rougeL': Score(precision=0.046579330422125184, recall=0.043184885290148446, fmeasure=0.04481792717086834)}
************************************
tensor([[50257,   220, 50257,  8865,  3827, 34787,    27,    91,  5188,    47,
            91,    29, 42276,   262,  1402, 33486,  2779,  5473,   257,  7348,
          1221,  2800,  1468,  9846, 42281, 29663,  1056, 22818,  1489, 26730,
         12840, 10441,    12,  2339, 34870,   911,  1236,   447,   247,    82,
            27,    91,  5188,    47,    91,    29]], device='cuda:0')
  Storm Over Warlock<|SEP|>crew the small Terran base refuge a flying disc contact old memories downed scoutship explode booby trap dragon-like humanoid Shann’s<|SEP|>A group of explorers, led by the enigmatic Dr. Goodwin, investigate a mysterious dead trail leading to a vast expansive plain, which some suggest to be a giant, red giant narwhal.
The group disco

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.5166374781085814, recall=0.38612565445026176, fmeasure=0.4419475655430711), 'rougeL': Score(precision=0.18914185639229422, recall=0.14136125654450263, fmeasure=0.16179775280898878)}
************************************
tensor([[50257,   220, 50257,  5498, 39143,    27,    91,  5188,    47,    91,
            29,   305, 13645, 13767,   370,   633,  2277,  2972,  1180, 15807,
         35786, 28421,   262,   649,   530, 16359, 22153,  7448,  5387,  6147,
          4522, 16759,  7386,  4645,    27,    91,  5188,    47,    91,    29]],
       device='cuda:0')
  Second Variety<|SEP|>robot sophisticated Wound hit various different fortune nicknamed claws the new one automated Underground saved internal metal ID dishes domain structure<|SEP|>robots learn to spot and locate a variety of robots, mostly from outside the city. Intelligent robots have a habit of recognizing and recognizing unfamiliar faces, and recognize people with whom it converses.
The robots learn q

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


{'rouge1': Score(precision=0.45077720207253885, recall=0.33547557840616965, fmeasure=0.3846720707442889), 'rougeL': Score(precision=0.16062176165803108, recall=0.11953727506426735, fmeasure=0.13706705969049374)}
************************************
tensor([[50257,   220, 50257, 17917,    25, 48278,    27,    91,  5188,    47,
            91,    29, 11265,  5384,  2622, 18423,    82,   257,  1762, 13522,
          3708,  9314,   262,  1080,  6591,   649,  2761,   383, 35113,    12,
          2339, 16269,   753, 11970,  6821,  3612,    27,    91,  5188,    47,
            91,    29]], device='cuda:0')
